/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.EstadoProveedor;
import com.incloud.hcp.service.delta.EstadoProveedorDeltaService;
import com.incloud.hcp.service.impl.EstadoProveedorServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

/**
 * A simple DTO Facility for EstadoProveedor.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class EstadoProveedorDeltaServiceImpl extends EstadoProveedorServiceImpl implements EstadoProveedorDeltaService {

    /**************************/
    /* Metodos Personalizados */
    /**************************/



    /**************************/
    /* Metodos Generados      */
    /**************************/

    protected Sort setFindAll(Sort sort) {
        return sort;
    }

    protected Sort setFind(EstadoProveedor req, ExampleMatcher matcher, Example<EstadoProveedor> example, Sort sort) {
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<EstadoProveedor> req, ExampleMatcher matcher, Example<EstadoProveedor> example) {
        return;
    }

    protected void setCreate(EstadoProveedor dto) {

    }

    protected void setSave(EstadoProveedor dto) {

    }

    protected void setDelete(Integer id) {

    }

    protected void setDeleteAll() {

    }

}