/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.ProveedorPreguntaInformacion;
import com.incloud.hcp.dto.PreguntaInformacionInDto;
import com.incloud.hcp.dto.PreguntaInformacionOutDto;
import com.incloud.hcp.myibatis.mapper.ProveedorPreguntaInformacionMapper;
import com.incloud.hcp.service.delta.ProveedorPreguntaInformacionDeltaService;
import com.incloud.hcp.service.impl.ProveedorPreguntaInformacionServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

/**
 * A simple DTO Facility for ProveedorPreguntaInformacion.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class ProveedorPreguntaInformacionDeltaServiceImpl extends ProveedorPreguntaInformacionServiceImpl implements ProveedorPreguntaInformacionDeltaService {


    /**************************/
    /* Metodos Personalizados */
    /**************************/

    @Autowired
    private ProveedorPreguntaInformacionMapper proveedorPreguntaInformacionMapper;

    @Override
    public PreguntaInformacionOutDto crearPreguntaInformacion(PreguntaInformacionInDto bean) {
        PreguntaInformacionOutDto result = new PreguntaInformacionOutDto();
        PreguntaInformacionInDto beanCentro = new PreguntaInformacionInDto();

        beanCentro.setIdPreguntaInformacion(bean.getIdPreguntaInformacion());
        beanCentro.setRespuesta(bean.getRespuesta());
        beanCentro.setPreguntaInformacion(bean.getPreguntaInformacion());
        beanCentro.setProveedor(bean.getProveedor());

        if(beanCentro.getIdPreguntaInformacion() != null){
            proveedorPreguntaInformacionMapper.updateProveedorPreguntaInformacionV2(beanCentro);

            result.setIdPreguntaInformacion(bean.getIdPreguntaInformacion());
            result.setRespuesta(bean.getRespuesta());
            result.setPreguntaInformacion(bean.getPreguntaInformacion());
            result.setProveedor(bean.getProveedor());
        }else {
            Integer validarId = proveedorPreguntaInformacionMapper.getIdSequence();
            beanCentro.setIdPreguntaInformacion(validarId);
            proveedorPreguntaInformacionMapper.getCrearProveedorPreguntaInformacion(beanCentro);

            result.setIdPreguntaInformacion(validarId);
            result.setRespuesta(bean.getRespuesta());
            result.setPreguntaInformacion(bean.getPreguntaInformacion());
            result.setProveedor(bean.getProveedor());
        }

        return result;
    }

    /**************************/
    /* Metodos Generados      */
    /**************************/

    protected Sort setFindAll(Sort sort) {
        return sort;
    }

    protected Sort setFind(ProveedorPreguntaInformacion req, ExampleMatcher matcher, Example<ProveedorPreguntaInformacion> example, Sort sort) {
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<ProveedorPreguntaInformacion> req, ExampleMatcher matcher,
            Example<ProveedorPreguntaInformacion> example) {
        return;
    }

    protected void setCreate(ProveedorPreguntaInformacion dto) {

    }

    protected void setSave(ProveedorPreguntaInformacion dto) {

    }

    protected void setDelete(Integer id) {

    }

    protected void setDeleteAll() {

    }

}