/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.ProveedorFuncionario;
import com.incloud.hcp.dto.FuncionarioInDto;
import com.incloud.hcp.dto.FuncionarioOutDto;
import com.incloud.hcp.dto.InstalacionInDto;
import com.incloud.hcp.dto.InstalacionOutDto;
import com.incloud.hcp.myibatis.mapper.ProveedorFuncionarioMapper;
import com.incloud.hcp.myibatis.mapper.ProveedorInstalacionMapper;
import com.incloud.hcp.service.delta.ProveedorFuncionarioDeltaService;
import com.incloud.hcp.service.impl.ProveedorFuncionarioServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

/**
 * A simple DTO Facility for ProveedorFuncionario.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class ProveedorFuncionarioDeltaServiceImpl extends ProveedorFuncionarioServiceImpl implements ProveedorFuncionarioDeltaService {

    /**************************/
    /* Metodos Personalizados */
    /**************************/

    @Autowired
    private ProveedorFuncionarioMapper proveedorFuncionarioMapper;

    @Override
    public FuncionarioOutDto crearFuncionario(FuncionarioInDto bean) {
        FuncionarioOutDto result = new FuncionarioOutDto();
        FuncionarioInDto beanCentro = new FuncionarioInDto();

        beanCentro.setIdProveedorFuncionario(bean.getIdProveedorFuncionario());
        beanCentro.setApellidosNombres(bean.getApellidosNombres());
        beanCentro.setCargo(bean.getCargo());
        beanCentro.setRuc(bean.getRuc());
        beanCentro.setProveedor(bean.getProveedor());
        beanCentro.setTipoDocumento(bean.getTipoDocumento());

        if(beanCentro.getIdProveedorFuncionario() != null){
            proveedorFuncionarioMapper.updateFuncionario(beanCentro);

            result.setIdProveedorFuncionario(bean.getIdProveedorFuncionario());
            result.setApellidosNombres(bean.getApellidosNombres());
            result.setCargo(bean.getCargo());
            result.setRuc(bean.getRuc());
            result.setProveedor(bean.getProveedor());
            result.setTipoDocumento(bean.getTipoDocumento());
        }else{
            Integer validarId = proveedorFuncionarioMapper.getIdSequence();
            beanCentro.setIdProveedorFuncionario(validarId);
            proveedorFuncionarioMapper.getCrearFuncionario(beanCentro);

            result.setIdProveedorFuncionario(validarId);
            result.setApellidosNombres(bean.getApellidosNombres());
            result.setCargo(bean.getCargo());
            result.setRuc(bean.getRuc());
            result.setProveedor(bean.getProveedor());
            result.setTipoDocumento(bean.getTipoDocumento());
        }

        return result;
    }

    /**************************/
    /* Metodos Generados      */
    /**************************/

    protected Sort setFindAll(Sort sort) {
        return sort;
    }

    protected Sort setFind(ProveedorFuncionario req, ExampleMatcher matcher, Example<ProveedorFuncionario> example, Sort sort) {
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<ProveedorFuncionario> req, ExampleMatcher matcher, Example<ProveedorFuncionario> example) {
        return;
    }

    protected void setCreate(ProveedorFuncionario dto) {

    }

    protected void setSave(ProveedorFuncionario dto) {

    }

    protected void setDelete(Integer id) {

    }

    protected void setDeleteAll() {

    }

}