/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.ProveedorInstalacion;
import com.incloud.hcp.dto.InstalacionInDto;
import com.incloud.hcp.dto.InstalacionOutDto;
import com.incloud.hcp.dto.PreguntaInformacionInDto;
import com.incloud.hcp.dto.PreguntaInformacionOutDto;
import com.incloud.hcp.myibatis.mapper.ProveedorInstalacionMapper;
import com.incloud.hcp.myibatis.mapper.ProveedorPreguntaInformacionMapper;
import com.incloud.hcp.service.delta.ProveedorInstalacionDeltaService;
import com.incloud.hcp.service.impl.ProveedorInstalacionServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

/**
 * A simple DTO Facility for ProveedorInstalacion.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class ProveedorInstalacionDeltaServiceImpl extends ProveedorInstalacionServiceImpl implements ProveedorInstalacionDeltaService {

    /**************************/
    /* Metodos Personalizados */
    /**************************/

    @Autowired
    private ProveedorInstalacionMapper proveedorInstalacionMapper;

    @Override
    public InstalacionOutDto crearInstalacion(InstalacionInDto bean) {
        InstalacionOutDto result = new InstalacionOutDto();
        InstalacionInDto beanCentro = new InstalacionInDto();

        beanCentro.setIdProveedorInstalacion(bean.getIdProveedorInstalacion());
        beanCentro.setCodigoTipoInstalacion(bean.getCodigoTipoInstalacion());
        beanCentro.setDireccion(bean.getDireccion());
        beanCentro.setTelefono(bean.getTelefono());
        beanCentro.setProveedor(bean.getProveedor());

        if(beanCentro.getIdProveedorInstalacion() != null){
            proveedorInstalacionMapper.updateInstalacion(beanCentro);

            result.setIdProveedorInstalacion(bean.getIdProveedorInstalacion());
            result.setCodigoTipoInstalacion(bean.getCodigoTipoInstalacion());
            result.setDireccion(bean.getDireccion());
            result.setTelefono(bean.getTelefono());
            result.setProveedor(bean.getProveedor());
        }else{
            Integer validarId = proveedorInstalacionMapper.getIdSequence();
            beanCentro.setIdProveedorInstalacion(validarId);
            proveedorInstalacionMapper.getCrearInstalacion(beanCentro);

            result.setIdProveedorInstalacion(validarId);
            result.setCodigoTipoInstalacion(bean.getCodigoTipoInstalacion());
            result.setDireccion(bean.getDireccion());
            result.setTelefono(bean.getTelefono());
            result.setProveedor(bean.getProveedor());
        }

        return result;
    }

    /**************************/
    /* Metodos Generados      */
    /**************************/

    protected Sort setFindAll(Sort sort) {
        return sort;
    }

    protected Sort setFind(ProveedorInstalacion req, ExampleMatcher matcher, Example<ProveedorInstalacion> example, Sort sort) {
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<ProveedorInstalacion> req, ExampleMatcher matcher, Example<ProveedorInstalacion> example) {
        return;
    }

    protected void setCreate(ProveedorInstalacion dto) {

    }

    protected void setSave(ProveedorInstalacion dto) {

    }

    protected void setDelete(Integer id) {

    }

    protected void setDeleteAll() {

    }

}