/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.incloud.hcp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import java.util.Date;

@StaticMetamodel(AppProcesoLog.class)
public abstract class AppProcesoLog_ {

    // Raw attributes
    public static volatile SingularAttribute<AppProcesoLog, Integer> id;
    public static volatile SingularAttribute<AppProcesoLog, Date> fechaInicioEjecucion;
    public static volatile SingularAttribute<AppProcesoLog, Date> fechaFinEjecucion;
    public static volatile SingularAttribute<AppProcesoLog, String> estadoEjecucion;
    public static volatile SingularAttribute<AppProcesoLog, String> descripcionEstadoEjecucion;
    public static volatile SingularAttribute<AppProcesoLog, String> claseProgramacion;
    public static volatile SingularAttribute<AppProcesoLog, String> metodoProgramacion;
    public static volatile SingularAttribute<AppProcesoLog, String> parametroEntrada;
    public static volatile SingularAttribute<AppProcesoLog, String> resultadoSalida;
    public static volatile SingularAttribute<AppProcesoLog, String> usuario;
    public static volatile SingularAttribute<AppProcesoLog, Long> duracionMs;
}