/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.incloud.hcp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(CotizacionAdjuntoRechazada.class)
public abstract class CotizacionAdjuntoRechazada_ {

    // Raw attributes
    public static volatile SingularAttribute<CotizacionAdjuntoRechazada, Integer> id;
    public static volatile SingularAttribute<CotizacionAdjuntoRechazada, String> archivoId;
    public static volatile SingularAttribute<CotizacionAdjuntoRechazada, String> archivoNombre;
    public static volatile SingularAttribute<CotizacionAdjuntoRechazada, String> archivoTipo;
    public static volatile SingularAttribute<CotizacionAdjuntoRechazada, String> descripcion;
    public static volatile SingularAttribute<CotizacionAdjuntoRechazada, String> indCotizacion;
    public static volatile SingularAttribute<CotizacionAdjuntoRechazada, String> rutaAdjunto;

    // Many to one
    public static volatile SingularAttribute<CotizacionAdjuntoRechazada, CotizacionRechazada> idCotizacionRechazada;
}