/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.incloud.hcp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import java.math.BigDecimal;
import java.util.Date;

@StaticMetamodel(CotizacionRechazada.class)
public abstract class CotizacionRechazada_ {

    // Raw attributes
    public static volatile SingularAttribute<CotizacionRechazada, Integer> id;
    public static volatile SingularAttribute<CotizacionRechazada, String> estadoCotizacion;
    public static volatile SingularAttribute<CotizacionRechazada, Date> fechaCreacion;
    public static volatile SingularAttribute<CotizacionRechazada, Date> fechaModificacion;
    public static volatile SingularAttribute<CotizacionRechazada, Date> fechaRechazo;
    public static volatile SingularAttribute<CotizacionRechazada, BigDecimal> importeTotal;
    public static volatile SingularAttribute<CotizacionRechazada, String> indGanador;
    public static volatile SingularAttribute<CotizacionRechazada, Integer> usuarioCreacion;
    public static volatile SingularAttribute<CotizacionRechazada, Integer> usuarioModificacion;

    // Many to one
    public static volatile SingularAttribute<CotizacionRechazada, Proveedor> idProveedor;
    public static volatile SingularAttribute<CotizacionRechazada, Moneda> idMoneda;
    public static volatile SingularAttribute<CotizacionRechazada, Licitacion> idLicitacion;
}