/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.incloud.hcp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import java.math.BigDecimal;

@StaticMetamodel(CotizacionDetalleRechazada.class)
public abstract class CotizacionDetalleRechazada_ {

    // Raw attributes
    public static volatile SingularAttribute<CotizacionDetalleRechazada, Integer> id;
    public static volatile SingularAttribute<CotizacionDetalleRechazada, BigDecimal> cantidadCotizada;
    public static volatile SingularAttribute<CotizacionDetalleRechazada, BigDecimal> cantidadSolicitada;
    public static volatile SingularAttribute<CotizacionDetalleRechazada, String> descripcion;
    public static volatile SingularAttribute<CotizacionDetalleRechazada, String> especificacion;
    public static volatile SingularAttribute<CotizacionDetalleRechazada, String> indGanador;
    public static volatile SingularAttribute<CotizacionDetalleRechazada, String> numeroParte;
    public static volatile SingularAttribute<CotizacionDetalleRechazada, BigDecimal> precioUnitario;
    public static volatile SingularAttribute<CotizacionDetalleRechazada, String> solicitudPedido;

    // Many to one
    public static volatile SingularAttribute<CotizacionDetalleRechazada, UnidadMedida> idUnidadMedida;
    public static volatile SingularAttribute<CotizacionDetalleRechazada, BienServicio> idBienServicio;
    public static volatile SingularAttribute<CotizacionDetalleRechazada, LicitacionDetalle> idLicitacionDetalle;
    public static volatile SingularAttribute<CotizacionDetalleRechazada, CotizacionRechazada> idCotizacionRechazada;
}