/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.incloud.hcp.domain._framework.BaseDomain;
import com.incloud.hcp.domain._framework.Identifiable;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.logging.Logger;


@Entity
@Table(name = "estado_proveedor")
@JsonIgnoreProperties(ignoreUnknown = true)
public class EstadoProveedor extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(EstadoProveedor.class.getName());

    // Raw attributes
    private Integer id;
    private String descripcionEstadoProveedor;
    private Integer orden;
    private String codigoEstadoProveedor;
    private String indVerValidacion;
    private String indVerLicitacion;

    @Override
    public String entityClassName() {
        return EstadoProveedor.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "id_estado_proveedor", precision = 10)
    @Id
    //@GeneratedValue(strategy = SEQUENCE, generator = "seq_estado_proveedor")
    //@SequenceGenerator(name = "seq_estado_proveedor", sequenceName = "seq_estado_proveedor", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public EstadoProveedor id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [descripcionEstadoProveedor] ------------------------

    @NotEmpty
    @Size(max = 60)
    @Column(name = "descripcion_estado_proveedor", nullable = false, unique = true, length = 60)
    public String getDescripcionEstadoProveedor() {
        return descripcionEstadoProveedor;
    }

    public void setDescripcionEstadoProveedor(String descripcionEstadoProveedor) {
        this.descripcionEstadoProveedor = descripcionEstadoProveedor;
    }

    public EstadoProveedor descripcionEstadoProveedor(String descripcionEstadoProveedor) {
        setDescripcionEstadoProveedor(descripcionEstadoProveedor);
        return this;
    }
    // -- [orden] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "orden", precision = 10)
    public Integer getOrden() {
        return orden;
    }

    public void setOrden(Integer orden) {
        this.orden = orden;
    }

    public EstadoProveedor orden(Integer orden) {
        setOrden(orden);
        return this;
    }
    // -- [codigoEstadoProveedor] ------------------------

    @NotEmpty
    @Size(max = 3)
    @Column(name = "codigo_estado_proveedor", nullable = false, unique = true, length = 3)
    public String getCodigoEstadoProveedor() {
        return codigoEstadoProveedor;
    }

    public void setCodigoEstadoProveedor(String codigoEstadoProveedor) {
        this.codigoEstadoProveedor = codigoEstadoProveedor;
    }

    public EstadoProveedor codigoEstadoProveedor(String codigoEstadoProveedor) {
        setCodigoEstadoProveedor(codigoEstadoProveedor);
        return this;
    }
    // -- [indVerValidacion] ------------------------

    @Size(max = 1)
    @Column(name = "ind_ver_validacion", length = 1)
    public String getIndVerValidacion() {
        return indVerValidacion;
    }

    public void setIndVerValidacion(String indVerValidacion) {
        this.indVerValidacion = indVerValidacion;
    }

    public EstadoProveedor indVerValidacion(String indVerValidacion) {
        setIndVerValidacion(indVerValidacion);
        return this;
    }

    // -- [indVerLicitacion] ------------------------

    @Size(max = 1)
    @Column(name = "ind_ver_licitacion", length = 1)
    public String getIndVerLicitacion() {
        return indVerLicitacion;
    }

    public void setIndVerLicitacion(String indVerLicitacion) {
        this.indVerLicitacion = indVerLicitacion;
    }

    public EstadoProveedor indVerLicitacion(String indVerLicitacion) {
        setIndVerValidacion(indVerLicitacion);
        return this;
    }

    /**
     * Apply the default values.
     */
    public EstadoProveedor withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof EstadoProveedor && hashCode() == other.hashCode());
    }


    @Override
    public String toString() {
        return "EstadoProveedor{" +
                "id=" + id +
                ", descripcionEstadoProveedor='" + descripcionEstadoProveedor + '\'' +
                ", orden=" + orden +
                ", codigoEstadoProveedor='" + codigoEstadoProveedor + '\'' +
                ", indVerValidacion='" + indVerValidacion + '\'' +
                ", indVerLicitacion='" + indVerLicitacion + '\'' +
                '}';
    }
}