/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.google.common.base.MoreObjects;
import com.incloud.hcp.domain._framework.BaseDomain;
import com.incloud.hcp.domain._framework.Identifiable;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.Date;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;
import static javax.persistence.TemporalType.TIMESTAMP;

@Entity
@Table(name = "peso_linea_comercial_aprobacion")
public class PesoLineaComercialAprobacion extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(PesoLineaComercialAprobacion.class.getName());

    // Raw attributes
    private Integer id;
    private Date fechaVigencia;

    // Many to one
    private Usuario idUsuario;
    private PesoLineaComercial idPesoLineaComercial;

    @Override
    public String entityClassName() {
        return PesoLineaComercialAprobacion.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "id_peso_linea_comercial_aprobacion", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_peso_linea_comercial_aprobacion")
    @Id
    @SequenceGenerator(name = "seq_peso_linea_comercial_aprobacion", sequenceName = "seq_peso_linea_comercial_aprobacion", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public PesoLineaComercialAprobacion id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [fechaVigencia] ------------------------

    @NotNull
    @Column(name = "fecha_vigencia", nullable = false, length = 29)
    @Temporal(TIMESTAMP)
    public Date getFechaVigencia() {
        return fechaVigencia;
    }

    public void setFechaVigencia(Date fechaVigencia) {
        this.fechaVigencia = fechaVigencia;
    }

    public PesoLineaComercialAprobacion fechaVigencia(Date fechaVigencia) {
        setFechaVigencia(fechaVigencia);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: PesoLineaComercialAprobacion.idUsuario ==> Usuario.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "id_usuario", nullable = false)
    @ManyToOne
    public Usuario getIdUsuario() {
        return idUsuario;
    }

    /**
     * Set the {@link #idUsuario} without adding this PesoLineaComercialAprobacion instance on the passed {@link #idUsuario}
     */
    public void setIdUsuario(Usuario idUsuario) {
        this.idUsuario = idUsuario;
    }

    public PesoLineaComercialAprobacion idUsuario(Usuario idUsuario) {
        setIdUsuario(idUsuario);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: PesoLineaComercialAprobacion.idPesoLineaComercial ==> PesoLineaComercial.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "id_peso_linea_comercial", nullable = false)
    @ManyToOne
    public PesoLineaComercial getIdPesoLineaComercial() {
        return idPesoLineaComercial;
    }

    /**
     * Set the {@link #idPesoLineaComercial} without adding this PesoLineaComercialAprobacion instance on the passed {@link #idPesoLineaComercial}
     */
    public void setIdPesoLineaComercial(PesoLineaComercial idPesoLineaComercial) {
        this.idPesoLineaComercial = idPesoLineaComercial;
    }

    public PesoLineaComercialAprobacion idPesoLineaComercial(PesoLineaComercial idPesoLineaComercial) {
        setIdPesoLineaComercial(idPesoLineaComercial);
        return this;
    }

    /**
     * Apply the default values.
     */
    public PesoLineaComercialAprobacion withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof PesoLineaComercialAprobacion && hashCode() == other.hashCode());
    }


    /**
     * Construct a readable string representation for this PesoLineaComercialAprobacion instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("fechaVigencia", getFechaVigencia()) //
                .toString();
    }
}