/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.incloud.hcp.domain._framework.BaseDomain;
import com.incloud.hcp.domain._framework.Identifiable;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "pre_registro_linea_comercial")
public class PreRegistroLineaComercial extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(PreRegistroLineaComercial.class.getName());

    // Raw attributes
    private Integer id;
    private Integer idNumberLineaComercial;
    private Integer idNumberRegistro;
    private Integer idNumberFamilia;
    private String descripcionLineaComercial;
    @Column(name = "id_padre")
    private Integer idPadre;

    // Many to one
    private LineaComercial idLineaComercial;
    private PreRegistroProveedor idRegistro;
    private LineaComercial idFamilia;

    @Override
    public String entityClassName() {
        return PreRegistroLineaComercial.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "id_pre_registro_linea_comercial", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_pre_registro_linea_comercial")
    @Id
    @SequenceGenerator(name = "seq_pre_registro_linea_comercial", sequenceName = "seq_pre_registro_linea_comercial", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public PreRegistroLineaComercial id(Integer id) {
        setId(id);
        return this;
    }

    @NotNull
    @Column(name = "id_linea_comercial", nullable = false)
    public Integer getIdNumberLineaComercial() {
        return idNumberLineaComercial;
    }

    public void setIdNumberLineaComercial(Integer idNumberLineaComercial) {
        this.idNumberLineaComercial = idNumberLineaComercial;
    }

    @NotNull
    @Column(name = "id_registro", nullable = false)
    public Integer getIdNumberRegistro() {
        return idNumberRegistro;
    }

    public void setIdNumberRegistro(Integer idNumberRegistro) {
        this.idNumberRegistro = idNumberRegistro;
    }

    @NotNull
    @Column(name = "id_familia", nullable = false)
    public Integer getIdNumberFamilia() {
        return idNumberFamilia;
    }


    public Integer getIdPadre() {
        return idPadre;
    }

    public void setIdPadre(Integer idPadre) {
        this.idPadre = idPadre;
    }


    

    public void setIdNumberFamilia(Integer idNumberFamilia) {
        this.idNumberFamilia = idNumberFamilia;
    }

    @Column(name = "descripcion_linea_comercial")
    public String getDescripcionLineaComercial() {
        return descripcionLineaComercial;
    }

    public void setDescripcionLineaComercial(String descripcionLineaComercial) {
        this.descripcionLineaComercial = descripcionLineaComercial;
    }
    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: PreRegistroLineaComercial.idLineaComercial ==> LineaComercial.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

//    @NotNull
    @JoinColumn(name = "id_linea_comercial", insertable = false, updatable = false)
    @ManyToOne
    public LineaComercial getIdLineaComercial() {
        return idLineaComercial;
    }

    /**
     * Set the {@link #idLineaComercial} without adding this PreRegistroLineaComercial instance on the passed {@link #idLineaComercial}
     */
    public void setIdLineaComercial(LineaComercial idLineaComercial) {
        this.idLineaComercial = idLineaComercial;
    }

    public PreRegistroLineaComercial idLineaComercial(LineaComercial idLineaComercial) {
        setIdLineaComercial(idLineaComercial);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: PreRegistroLineaComercial.idRegistro ==> PreRegistroProveedor.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

//    @NotNull
    @JoinColumn(name = "id_registro", insertable = false, updatable = false)
    @ManyToOne
    public PreRegistroProveedor getIdRegistro() {
        return idRegistro;
    }

    /**
     * Set the {@link #idRegistro} without adding this PreRegistroLineaComercial instance on the passed {@link #idRegistro}
     */
    public void setIdRegistro(PreRegistroProveedor idRegistro) {
        this.idRegistro = idRegistro;
    }

    public PreRegistroLineaComercial idRegistro(PreRegistroProveedor idRegistro) {
        setIdRegistro(idRegistro);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: PreRegistroLineaComercial.idFamilia ==> LineaComercial.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

//    @NotNull
    @JoinColumn(name = "id_familia", insertable = false, updatable = false)
    @ManyToOne
    public LineaComercial getIdFamilia() {
        return idFamilia;
    }

    /**
     * Set the {@link #idFamilia} without adding this PreRegistroLineaComercial instance on the passed {@link #idFamilia}
     */
    public void setIdFamilia(LineaComercial idFamilia) {
        this.idFamilia = idFamilia;
    }

    public PreRegistroLineaComercial idFamilia(LineaComercial idFamilia) {
        setIdFamilia(idFamilia);
        return this;
    }

    /**
     * Apply the default values.
     */
    public PreRegistroLineaComercial withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof PreRegistroLineaComercial && hashCode() == other.hashCode());
    }

    @Override
    public String toString() {
        return "PreRegistroLineaComercial{" +
                "id=" + id +
                ", idNumberLineaComercial=" + idNumberLineaComercial +
                ", idNumberRegistro=" + idNumberRegistro +
                ", idNumberFamilia=" + idNumberFamilia +
                ", idLineaComercial=" + idLineaComercial +
                ", idRegistro=" + idRegistro +
                ", idFamilia=" + idFamilia +
                ", idPadre=" + idPadre +
                ", descripcionLineaComercial=" + descripcionLineaComercial +
                '}';
    }
}