/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.incloud.hcp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(ProveedorCliente.class)
public abstract class ProveedorCliente_ {

    // Raw attributes
    public static volatile SingularAttribute<ProveedorCliente, Integer> id;
    public static volatile SingularAttribute<ProveedorCliente, String> codigoTipoProveedorCliente;
    public static volatile SingularAttribute<ProveedorCliente, String> razonSocial;
    public static volatile SingularAttribute<ProveedorCliente, String> ruc;
    public static volatile SingularAttribute<ProveedorCliente, String> rubro;
    public static volatile SingularAttribute<ProveedorCliente, Double> porcentajeParticipacion;
    public static volatile SingularAttribute<ProveedorCliente, String> personaContacto;
    public static volatile SingularAttribute<ProveedorCliente, String> telefono;
    public static volatile SingularAttribute<ProveedorCliente, String> email;

    // Many to one
    public static volatile SingularAttribute<ProveedorCliente, Proveedor> idProveedor;
}