/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.incloud.hcp.domain._framework.BaseDomain;
import com.incloud.hcp.domain._framework.Identifiable;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "proveedor_cliente")
public class ProveedorCliente extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(ProveedorCliente.class.getName());

    // Raw attributes
    @Column(name = "id_proveedor_cliente", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_proveedor_cliente")
    @Id
    @SequenceGenerator(name = "seq_proveedor_cliente", sequenceName = "seq_proveedor_cliente", allocationSize = 1)
    private Integer id;

    @NotEmpty
    @Size(max = 3)
    @Column(name = "codigo_tipo_proveedor_cliente", nullable = false, length = 3)
    private String codigoTipoProveedorCliente;

    @NotEmpty
    @Size(max = 160)
    @Column(name = "razon_social", nullable = false, length = 160)
    private String razonSocial;

    @NotEmpty
    @Size(max = 34) // 20
    @Column(name = "ruc", nullable = false, length = 34) // 20
    private String ruc;

    @NotEmpty
    @Size(max = 100)
    @Column(name = "rubro", nullable = false, length = 100)
    private String rubro;

    @Digits(integer = 3, fraction = 2)
    @Column(name = "porcentaje_participacion", precision = 5, scale = 2)
    private Double porcentajeParticipacion;

    @Size(max = 255)
    @Column(name = "persona_contacto")
    private String personaContacto;

    @Size(max = 30)
    @Column(name = "telefono", length = 30)
    private String telefono;

    @Email
    @Size(max = 100)
    @Column(name = "email", length = 100)
    private String email;

    // Many to one
    @NotNull
    @JoinColumn(name = "id_proveedor", nullable = false)
    @ManyToOne
    private Proveedor idProveedor;

    @Transient
    private String codigoTipoProveedorClienteText;

    @Transient
    private Integer idBuscarProveedor;

    @Override
    public String entityClassName() {
        return ProveedorCliente.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public ProveedorCliente id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [codigoTipoProveedorCliente] ------------------------
    public String getCodigoTipoProveedorCliente() {
        return codigoTipoProveedorCliente;
    }

    public void setCodigoTipoProveedorCliente(String codigoTipoProveedorCliente) {
        this.codigoTipoProveedorCliente = codigoTipoProveedorCliente;
    }

    public ProveedorCliente codigoTipoProveedorCliente(String codigoTipoProveedorCliente) {
        setCodigoTipoProveedorCliente(codigoTipoProveedorCliente);
        return this;
    }
    // -- [razonSocial] ------------------------
    public String getRazonSocial() {
        return razonSocial;
    }

    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    public ProveedorCliente razonSocial(String razonSocial) {
        setRazonSocial(razonSocial);
        return this;
    }
    // -- [ruc] ------------------------
    public String getRuc() {
        return ruc;
    }

    public void setRuc(String ruc) {
        this.ruc = ruc;
    }

    public ProveedorCliente ruc(String ruc) {
        setRuc(ruc);
        return this;
    }
    // -- [rubro] ------------------------
    public String getRubro() {
        return rubro;
    }

    public void setRubro(String rubro) {
        this.rubro = rubro;
    }

    public ProveedorCliente rubro(String rubro) {
        setRubro(rubro);
        return this;
    }
    // -- [porcentajeParticipacion] ------------------------
    public Double getPorcentajeParticipacion() {
        return porcentajeParticipacion;
    }

    public void setPorcentajeParticipacion(Double porcentajeParticipacion) {
        this.porcentajeParticipacion = porcentajeParticipacion;
    }

    public ProveedorCliente porcentajeParticipacion(Double porcentajeParticipacion) {
        setPorcentajeParticipacion(porcentajeParticipacion);
        return this;
    }
    // -- [personaContacto] ------------------------
    public String getPersonaContacto() {
        return personaContacto;
    }

    public void setPersonaContacto(String personaContacto) {
        this.personaContacto = personaContacto;
    }

    public ProveedorCliente personaContacto(String personaContacto) {
        setPersonaContacto(personaContacto);
        return this;
    }
    // -- [telefono] ------------------------
    public String getTelefono() {
        return telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public ProveedorCliente telefono(String telefono) {
        setTelefono(telefono);
        return this;
    }
    // -- [email] ------------------------
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public ProveedorCliente email(String email) {
        setEmail(email);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: ProveedorCliente.idProveedor ==> Proveedor.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    public Proveedor getIdProveedor() {
        return idProveedor;
    }

    /**
     * Set the {@link #idProveedor} without adding this ProveedorCliente instance on the passed {@link #idProveedor}
     */
    public void setIdProveedor(Proveedor idProveedor) {
        this.idProveedor = idProveedor;
    }

    public ProveedorCliente idProveedor(Proveedor idProveedor) {
        setIdProveedor(idProveedor);
        return this;
    }

    /**
     * Apply the default values.
     */
    public ProveedorCliente withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof ProveedorCliente && hashCode() == other.hashCode());
    }


    public String getCodigoTipoProveedorClienteText() {
        return codigoTipoProveedorClienteText;
    }

    public void setCodigoTipoProveedorClienteText(String codigoTipoProveedorClienteText) {
        this.codigoTipoProveedorClienteText = codigoTipoProveedorClienteText;
    }

    public Integer getIdBuscarProveedor() {
        return idBuscarProveedor;
    }

    public void setIdBuscarProveedor(Integer idBuscarProveedor) {
        this.idBuscarProveedor = idBuscarProveedor;
    }

    @Override
    public String toString() {
        return "ProveedorCliente{" +
                "id=" + id +
                ", codigoTipoProveedorCliente='" + codigoTipoProveedorCliente + '\'' +
                ", razonSocial='" + razonSocial + '\'' +
                ", ruc='" + ruc + '\'' +
                ", rubro='" + rubro + '\'' +
                ", porcentajeParticipacion=" + porcentajeParticipacion +
                ", personaContacto='" + personaContacto + '\'' +
                ", telefono='" + telefono + '\'' +
                ", email='" + email + '\'' +
                ", idProveedor=" + idProveedor +
                ", codigoTipoProveedorClienteText='" + codigoTipoProveedorClienteText + '\'' +
                ", idBuscarProveedor=" + idBuscarProveedor +
                '}';
    }
}