/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.incloud.hcp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Subetapa.class)
public abstract class Subetapa_ {

    // Raw attributes
    public static volatile SingularAttribute<Subetapa, Integer> id;
    public static volatile SingularAttribute<Subetapa, String> descripcionSubetapa;
    public static volatile SingularAttribute<Subetapa, String> indConfirmacionParticipacion;
    public static volatile SingularAttribute<Subetapa, String> indObligatorio;
    public static volatile SingularAttribute<Subetapa, String> indRenegociacion;
    public static volatile SingularAttribute<Subetapa, String> indEnvioCorreoRecordatorio;
    public static volatile SingularAttribute<Subetapa, Integer> diasEnvioCorreoRecordatorio;
    public static volatile SingularAttribute<Subetapa, String> indRecepcionConsulta;
    public static volatile SingularAttribute<Subetapa, String> indAbsolucionConsulta;
    public static volatile SingularAttribute<Subetapa, String> indFechaReferencial;
    public static volatile SingularAttribute<Subetapa, String> indSubetapaFinal;
    public static volatile SingularAttribute<Subetapa, Integer> orden;
}