/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.incloud.hcp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import java.math.BigDecimal;
import java.util.Date;

@StaticMetamodel(TasaCambio.class)
public abstract class TasaCambio_ {

    // Raw attributes
    public static volatile SingularAttribute<TasaCambio, Integer> id;
    public static volatile SingularAttribute<TasaCambio, Date> fechaTasa;
    public static volatile SingularAttribute<TasaCambio, BigDecimal> valor;

    // Many to one
    public static volatile SingularAttribute<TasaCambio, Moneda> idMonedaOrigen;
    public static volatile SingularAttribute<TasaCambio, Moneda> idMonedaDestino;
}