/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.incloud.hcp.domain._framework.BaseDomain;
import com.incloud.hcp.domain._framework.Identifiable;

import javax.persistence.*;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "USUARIO_CARGO", uniqueConstraints = {
    @UniqueConstraint(name = "usuario_cargo_ak01", columnNames = { "ID_USUARIO", "ID_CARGO" }) })
public class UsuarioCargo extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(UsuarioCargo.class.getName());

    private Integer id;
    private Integer idUsuario;
    private Integer idCargo;
    private Cargo cargo;

    @Override
    public String entityClassName() {
        return UsuarioCargo.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Id
    @Column(name = "ID_USUARIO_CARGO", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "USUARIO_CARGO_ID_SEQ")
    @SequenceGenerator(name = "USUARIO_CARGO_ID_SEQ", sequenceName = "USUARIO_CARGO_ID_SEQ", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public UsuarioCargo id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }


    @Column(name = "ID_USUARIO")
    public Integer getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    @Column(name = "ID_CARGO")
    public Integer getIdCargo() {
        return idCargo;
    }

    public void setIdCargo(Integer idCargo) {
        this.idCargo = idCargo;
    }

    @ManyToOne(fetch = FetchType.LAZY, targetEntity = Cargo.class)
    @JoinColumn(name = "ID_CARGO", referencedColumnName = "ID_CARGO", insertable = false, updatable = false)
    public Cargo getCargo() {
        return cargo;
    }

    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }


}