/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.google.common.base.MoreObjects;
import com.incloud.hcp.domain._framework.BaseDomain;
import com.incloud.hcp.domain._framework.Identifiable;
import com.incloud.hcp.validation.FixedLength;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "usuario_linea_comercial", uniqueConstraints = {
        @UniqueConstraint(name = "usuario_linea_comercial_ak01", columnNames = { "id_usuario", "id_linea_comercial" }) })
public class UsuarioLineaComercial extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(UsuarioLineaComercial.class.getName());

    // Raw attributes
    private Integer id;
    private String activo;

    // Many to one
    private Usuario idUsuario;
    private LineaComercial idLineaComercial;

    @Override
    public String entityClassName() {
        return UsuarioLineaComercial.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "id_usuario_linea_comercial", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_usuario_linea_comercial")
    @Id
    @SequenceGenerator(name = "seq_usuario_linea_comercial", sequenceName = "seq_usuario_linea_comercial", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public UsuarioLineaComercial id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [activo] ------------------------

    @FixedLength(length = 1)
    @Column(name = "activo", length = 1)
    public String getActivo() {
        return activo;
    }

    public void setActivo(String activo) {
        this.activo = activo;
    }

    public UsuarioLineaComercial activo(String activo) {
        setActivo(activo);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: UsuarioLineaComercial.idUsuario ==> Usuario.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "id_usuario", nullable = false)
    @ManyToOne
    public Usuario getIdUsuario() {
        return idUsuario;
    }

    /**
     * Set the {@link #idUsuario} without adding this UsuarioLineaComercial instance on the passed {@link #idUsuario}
     */
    public void setIdUsuario(Usuario idUsuario) {
        this.idUsuario = idUsuario;
    }

    public UsuarioLineaComercial idUsuario(Usuario idUsuario) {
        setIdUsuario(idUsuario);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: UsuarioLineaComercial.idLineaComercial ==> LineaComercial.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "id_linea_comercial", nullable = false)
    @ManyToOne
    public LineaComercial getIdLineaComercial() {
        return idLineaComercial;
    }

    /**
     * Set the {@link #idLineaComercial} without adding this UsuarioLineaComercial instance on the passed {@link #idLineaComercial}
     */
    public void setIdLineaComercial(LineaComercial idLineaComercial) {
        this.idLineaComercial = idLineaComercial;
    }

    public UsuarioLineaComercial idLineaComercial(LineaComercial idLineaComercial) {
        setIdLineaComercial(idLineaComercial);
        return this;
    }

    /**
     * Apply the default values.
     */
    public UsuarioLineaComercial withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof UsuarioLineaComercial && hashCode() == other.hashCode());
    }


    /**
     * Construct a readable string representation for this UsuarioLineaComercial instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("activo", getActivo()) //
                .toString();
    }
}