CREATE SEQUENCE seq_app_proceso_log
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;


CREATE SEQUENCE "PRE_REGISTRO_PROVEEDOR_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

	CREATE SEQUENCE "SEQ_PRE_REGISTRO_LINEA_COMERCIAL"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

	CREATE SEQUENCE "PROVEEDOR_HOMOLOGACION_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

	CREATE SEQUENCE "PROVEEDOR_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

	CREATE SEQUENCE "PROVEEDOR_LINEA_COMERCIAL_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

	CREATE SEQUENCE "SOLICITUD_BLACKLIST_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "BANCO_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "BIEN_SERVICIO_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "CCOMPARATIVO_ADJUDICADO_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "CCOMPARATIVO_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

-- CREATE SEQUENCE "CCOMPARATIVO_PUNTAJE_DETALLE_ID_SEQ"
-- 	START WITH 1
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	NO MAXVALUE
-- 	NO CYCLE
-- 	NO CACHE;

-- CREATE SEQUENCE "CCOMPARATIVO_PUNTAJE_ID_SEQ"
-- 	START WITH 1
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	NO MAXVALUE
-- 	NO CYCLE
-- 	NO CACHE;

CREATE SEQUENCE "CENTRO_ALMACEN_ID_SEQ"
	START WITH 127
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "CLASE_DOCUMENTO_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "CONDICION_LIC_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "CONDICION_LIC_RESPUESTA_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "CONDICION_PAGO_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "COTIZACION_ADJUNTO_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "COTIZACION_DETALLE_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "COTIZACION_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "CRITERIOS_BLACKLIST_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

-- CREATE SEQUENCE "GRUPO_CONDICION_LIC_ID_SEQ"
-- 	START WITH 1
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	NO MAXVALUE
-- 	NO CYCLE
-- 	NO CACHE;

CREATE SEQUENCE "GRUPO_CONDICION_LIC_RESPUESTA_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "HOMOLOGACION_ID_SEQ"
	START WITH 102
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "HOMOLOGACION_RESPUESTA_ID_SEQ"
	START WITH 205
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "INFORMACION_NOTICIA_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "SEQ_PREGUNTA_INFORMACION"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "LICITACION_ADJUNTO_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "LICITACION_DETALLE_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "LICITACION_GRUPO_CONDICION_LIC_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "LICITACION_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "LINEA_COMERCIAL_ID_SEQ"
	START WITH 445
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "LOG_APP_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "MONEDA_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "PARAMETROS_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "PROVEEDOR_CANAL_CONTACTO_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "PROVEEDOR_CATALOGO_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "PROVEEDOR_CUENTA_BANCARIA_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "PROVEEDOR_EVALUACION_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "PROVEEDOR_PRODUCTO_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "PROVEEDOR_TIPO_RETENCION_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "RUBRO_BIEN_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "SECTOR_TRABAJO_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "SOLICITUD_ADJUNTO_BLACKLIST_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "TIPO_COMPROBANTE_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "TIPO_INFORMACION_NOTICIA_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

-- CREATE SEQUENCE "TIPO_LICITACION_ID_SEQ"
-- 	START WITH 1
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	NO MAXVALUE
-- 	NO CYCLE
-- 	NO CACHE;

CREATE SEQUENCE "TIPO_PROVEEDOR_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "TIPO_SOLICITUD_BLACKLIST_ID_SEQ"
	START WITH 4
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

-- CREATE SEQUENCE "UBIGEO_ID_SEQ"
-- 	START WITH 6428
-- 	INCREMENT BY 1
-- 	MINVALUE 1
-- 	NO MAXVALUE
-- 	NO CYCLE
-- 	NO CACHE;

CREATE SEQUENCE "UNIDAD_MEDIDA_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "USUARIO_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "USUARIO_CARGO_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "LICITACION_CONTROL_CAMBIO_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE "CONTROL_CAMBIO_CAMPO_ID_SEQ"
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE CARGO_ID_SEQ
	START WITH 0
	INCREMENT BY 1
	MINVALUE 0
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE SEQ_TIPO_DOCUMENTO_SAP
	START WITH 1
	INCREMENT BY 1
	MINVALUE 0
	NO MAXVALUE
	NO CYCLE
	NO CACHE;


CREATE SEQUENCE SEQ_TEMP_BIEN_SERVICIO
	START WITH 1
	INCREMENT BY 1
	MINVALUE 0
	NO MAXVALUE
	NO CYCLE
	NO CACHE;


CREATE SEQUENCE SEQ_TEMP_CENTRO_ALMACEN
	START WITH 1
	INCREMENT BY 1
	MINVALUE 0
	NO MAXVALUE
	NO CYCLE
	NO CACHE;

CREATE SEQUENCE SEQ_TEMP_RUBRO_BIEN
	START WITH 1
	INCREMENT BY 1
	MINVALUE 0
	NO MAXVALUE
	NO CYCLE
	NO CACHE;


/* ************ MODULO 1 *********************************** */
CREATE SEQUENCE ORDEN_COMPRA_ID_SEQ
 START WITH 1000
 INCREMENT BY 1
 NO MAXVALUE
 NO CYCLE
 NO CACHE;

CREATE SEQUENCE ORDEN_COMPRA_DETALLE_ID_SEQ
 START WITH 1000
 INCREMENT BY 1
 NO MAXVALUE
 NO CYCLE
 NO CACHE;

CREATE SEQUENCE ORDEN_COMPRA_DETALLE_TEXTO_ID_SEQ
 START WITH 1000
 INCREMENT BY 1
 NO MAXVALUE
 NO CYCLE
 NO CACHE;

CREATE SEQUENCE ORDEN_COMPRA_TEXTO_CABECERA_ID_SEQ
 START WITH 1000
 INCREMENT BY 1
 NO MAXVALUE
 NO CYCLE
 NO CACHE;

CREATE SEQUENCE DOCUMENTO_ACEPTACION_ID_SEQ
 START WITH 1000
 INCREMENT BY 1
 NO MAXVALUE
 NO CYCLE
 NO CACHE;

CREATE SEQUENCE DOCUMENTO_ACEPTACION_DETALLE_ID_SEQ
 START WITH 1000
 INCREMENT BY 1
 NO MAXVALUE
 NO CYCLE
 NO CACHE;

CREATE SEQUENCE PREFACTURA_ID_SEQ
 START WITH 1000
 INCREMENT BY 1
 NO MAXVALUE
 NO CYCLE
 NO CACHE;

CREATE SEQUENCE LOG_TRANSACCION_ID_SEQ
 START WITH 1000
 INCREMENT BY 1
 NO MAXVALUE
 NO CYCLE
 NO CACHE;

CREATE SEQUENCE ORDEN_COMPRA_DETALLE_TEXTO_REGISTRO_INFO_ID_SEQ
 START WITH 1000
 INCREMENT BY 1
 NO MAXVALUE
 NO CYCLE
 NO CACHE;

CREATE SEQUENCE ORDEN_COMPRA_DETALLE_TEXTO_MATERIAL_AMPLIADO_ID_SEQ
 START WITH 1000
 INCREMENT BY 1
 NO MAXVALUE
 NO CYCLE
 NO CACHE;
/* ********************************************************* */

