
package com.incloud.hcp.wsdl.solped;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_P026_ConsultaSOLPED_Req_Sync_Out", targetNamespace = "urn:sanmartinperu.pe:portal025:ConsultaSOLPED")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIP026ConsultaSOLPEDReqSyncOut {


    /**
     * 
     * @param mtP026ConsultaSOLPEDReqOut
     * @return
     *     returns com.solped.DTP026ConsultaSOLPEDRes
     */
    @WebMethod(operationName = "SI_P026_ConsultaSOLPED_Req_Sync_Out", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_P026_ConsultaSOLPED_Res_In", targetNamespace = "urn:sanmartinperu.pe:portal025:ConsultaSOLPED", partName = "MT_P026_ConsultaSOLPED_Res_In")
    public DTP026ConsultaSOLPEDRes siP026ConsultaSOLPEDReqSyncOut(
            @WebParam(name = "MT_P026_ConsultaSOLPED_Req_Out", targetNamespace = "urn:sanmartinperu.pe:portal025:ConsultaSOLPED", partName = "MT_P026_ConsultaSOLPED_Req_Out")
                    DTP026ConsultaSOLPEDReq mtP026ConsultaSOLPEDReqOut);

}
