
package com.incloud.hcp.wsdl.ordenCompra;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_v2_P031_CrearOrdenDeCompra_Sync_Req_OutService", targetNamespace = "urn:sanmartinperu.pe:portal031:CrearOrdendeCompra", wsdlLocation = "SI_v2_P031_CrearOrdenDeCompra_Sync_Req_OutService.wsdl")
public class SIV2P031CrearOrdenDeCompraSyncReqOutService
    extends Service
{

    private final static URL SIV2P031CREARORDENDECOMPRASYNCREQOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIV2P031CREARORDENDECOMPRASYNCREQOUTSERVICE_EXCEPTION;
    private final static QName SIV2P031CREARORDENDECOMPRASYNCREQOUTSERVICE_QNAME = new QName("urn:sanmartinperu.pe:portal031:CrearOrdendeCompra", "SI_v2_P031_CrearOrdenDeCompra_Sync_Req_OutService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("SI_v2_P031_CrearOrdenDeCompra_Sync_Req_OutService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIV2P031CREARORDENDECOMPRASYNCREQOUTSERVICE_WSDL_LOCATION = url;
        SIV2P031CREARORDENDECOMPRASYNCREQOUTSERVICE_EXCEPTION = e;
    }

    public SIV2P031CrearOrdenDeCompraSyncReqOutService() {
        super(__getWsdlLocation(), SIV2P031CREARORDENDECOMPRASYNCREQOUTSERVICE_QNAME);
    }

    public SIV2P031CrearOrdenDeCompraSyncReqOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIV2P031CREARORDENDECOMPRASYNCREQOUTSERVICE_QNAME, features);
    }

    public SIV2P031CrearOrdenDeCompraSyncReqOutService(URL wsdlLocation) {
        super(wsdlLocation, SIV2P031CREARORDENDECOMPRASYNCREQOUTSERVICE_QNAME);
    }

    public SIV2P031CrearOrdenDeCompraSyncReqOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIV2P031CREARORDENDECOMPRASYNCREQOUTSERVICE_QNAME, features);
    }

    public SIV2P031CrearOrdenDeCompraSyncReqOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIV2P031CrearOrdenDeCompraSyncReqOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIV2P031CrearOrdenDeCompraSyncReqOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIV2P031CrearOrdenDeCompraSyncReqOut getHTTPPort() {
        return super.getPort(new QName("urn:sanmartinperu.pe:portal031:CrearOrdendeCompra", "HTTP_Port"), SIV2P031CrearOrdenDeCompraSyncReqOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIV2P031CrearOrdenDeCompraSyncReqOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIV2P031CrearOrdenDeCompraSyncReqOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sanmartinperu.pe:portal031:CrearOrdendeCompra", "HTTP_Port"), SIV2P031CrearOrdenDeCompraSyncReqOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIV2P031CrearOrdenDeCompraSyncReqOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIV2P031CrearOrdenDeCompraSyncReqOut getHTTPSPort() {
        return super.getPort(new QName("urn:sanmartinperu.pe:portal031:CrearOrdendeCompra", "HTTPS_Port"), SIV2P031CrearOrdenDeCompraSyncReqOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIV2P031CrearOrdenDeCompraSyncReqOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIV2P031CrearOrdenDeCompraSyncReqOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sanmartinperu.pe:portal031:CrearOrdendeCompra", "HTTPS_Port"), SIV2P031CrearOrdenDeCompraSyncReqOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIV2P031CREARORDENDECOMPRASYNCREQOUTSERVICE_EXCEPTION!= null) {
            throw SIV2P031CREARORDENDECOMPRASYNCREQOUTSERVICE_EXCEPTION;
        }
        return SIV2P031CREARORDENDECOMPRASYNCREQOUTSERVICE_WSDL_LOCATION;
    }

}
