# PROFILE SPRING
spring.profiles.active=prd

#------------------------------------------------------------------------
#WAR COMPILE
##  mvn -Phcp package install -Dspring.profiles.active=dev
#------------------------------------------------------------------------

renegociacion.email = corptpt@topitop.com.pe
# LOG
logging.config=classpath:logback-${spring.profiles.active}.xml

# BUILD DATETIME
war.build.datetime=1900/01/01_00:00
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
server.error.include-message=always

##### Propiedades para el Multipart File ####
spring.servlet.multipart.max-file-size =  2000MB
spring.servlet.multipart.max-request-size = 2000MB
server.tomcat.max-swallow-size=-1

