server.port=8080
# SETTING PORTAL
sm.portal.dev=false
#Comprador
sm.portal.nameId =P003490
sm.portal.nameDisplay =Comprador 1
sm.portal.email = mmonsalve@csticorp.biz
log.proceso.enabled = true

email.enabled = true
#Proveedor
sm.portal.prov.idSCP=P00005
sm.portal.prov.ruc=20101256422
sm.portal.prov.nameDisplay = Proveedor 1 DEEV
sm.portal.prov.email = coropeza@csticorp.biz

#CMIS CLOU FOUNDRY
cmis.server=https://api-sdm-di.cfapps.us10.hana.ondemand.com/
cmis.cliente.id=sb-ce0d83ef-d875-4bc9-bcc1-3d852ebb9a33!b345445|sdm-di-DocumentManagement-sdm_integration!b6332
cmis.cliente.secret=d32b0fa3-d9c2-4153-babe-4d26add3dfcd$vh88SkwXwn5rkEsMOBY5hUh5VJDtt8r9VLQb85Z6Yls=
cmis.repository.id=e34ae14a-982c-4060-b3d2-768aed020232
cmis.server.credential=https://jrc-dev-kgr01psw.authentication.us10.hana.ondemand.com

# CMIS
sm.portal.cmis.name = iproviderRepositoryQas
sm.portal.cmis.key = iproviderRepositoryQas
cfg.portal.cmis.name = iproviderRepositoryQas
cfg.portal.cmis.key = iproviderRepositoryQas
destination.cmis = IPROVIDER_CMIS

#Folder ECM
cfg.folder.ecm = ArchivosSunat

#ClaveSol
cfg.sunat.user = 20100047056JAVIERT1
cfg.sunat.pass = Topy12

#URL PORTAL
#QA
cfg.portal.url.centenario = https://jrc-dev-qa-iprovider-ini1w0a8.launchpad.cfapps.us10.hana.ondemand.com/site?siteId=8760c77a-4e37-4018-a9b0-5be51fe91dec#Shell-home
cfg.portal.url = https://jrc-dev-qa-iprovider-ini1w0a8.launchpad.cfapps.us10.hana.ondemand.com/site?siteId=8760c77a-4e37-4018-a9b0-5be51fe91dec#Shell-home
cfg.portal.url.public.oc = https://jrc-dev-qa-iprovider-ini1w0a8.launchpad.cfapps.us10.hana.ondemand.com/site?siteId=8760c77a-4e37-4018-a9b0-5be51fe91dec#Shell-home
cfg.portal.url.activation = https://aabk1b9be.accounts.ondemand.com/saml2/idp/sso?sp=sp.accounts.sap.com&idp=https://aabk1b9be.accounts.ondemand.com

#WEBSERVICE PDF-XML COMPROBATE DE RETENCION
cfg.retencion.ws.url = http://qas.incloud.la:9998/services/S3getFilesCopeinca


#NOTIFICACIONES CONSULTAS URL
cfg.notificacion.consulta.url = noreplytpt@topitop.com.pe


# HANA (CLOUD) DB
# JPA / HIBERNATE
spring.jpa.properties.hibernate.format_sql=false
spring.datasource.driver-class-name=com.sap.db.jdbc.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.HANAColumnStoreDialect

## PRD
#spring.datasource.url = jdbc:sap://c5b64751-3982-4cbb-93cb-aed44abd9a2c.hna0.prod-us10.hanacloud.ondemand.com:443/?encrypt=true&ValidateCertificate=true
#spring.datasource.username = IPROVIDER
#spring.datasource.password = @Topytop2022


## QAS
spring.datasource.url = jdbc:sap://8bd71486-7b17-47d2-bd72-e2ce301cf1ad.hana.prod-us10.hanacloud.ondemand.com:443/?encrypt=true&ValidateCertificate=true
spring.datasource.username = IPROVIDER_DEV_QA
spring.datasource.password = Pa$$w0rd


destination.email = SEND_MAIL_IREQUEST

# PRIMARY DATA SOURCE
# HANA (CLOUD) DB
# (= create, update, none)
spring.jpa.hibernate.ddl-auto = update
spring.jta.enabled = true
spring.jpa.show-sql = true

# Hikari will use the above plus the following to setup connection pooling
spring.datasource.hikari.minimumIdle=2
spring.datasource.hikari.maximumPoolSize=10
spring.datasource.hikari.idleTimeout=3000
spring.datasource.hikari.poolName=SpringBootJPAHikariCP
spring.datasource.hikari.maxLifetime=20000
spring.datasource.hikari.connectionTimeout=3000

#cambio
##### Propiedades para el Multipart File ####
spring.servlet.multipart.max-file-size =  2000MB
spring.servlet.multipart.max-request-size = 2000MB
server.tomcat.max-swallow-size=-1

#DESTINATIONS
#-----------------------------------------

#DEV? 300
destination.rfc.profit=SAP_IPROVIDER_CLONING

#QAS 520
#destination.rfc.profit=CFG_DEST_RFC_QAS_520

# Email (Desactivar el bloque si email.enabled esta en false)

spring.mail.default-encoding=UTF-8

spring.mail.port=587

spring.mail.properties.mail.smtp.connecttimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.host=smtp-mail.outlook.com
spring.mail.password=MJ$Ing08$
spring.mail.username=muqui@jrcing.com.pe
spring.mail.properties.mail.store.protocol=pop3
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smpt.auth=true

#Credenciales API SAP
USERNAME_SAP = RMJ-IPA
PASSWORD_SAP = DzBpqubKhGleURSvZGVqNXoPt4mRCAseYehGus}t
#API_URL_SAP = https://my417543-api.s4hana.cloud.sap //DEV
#//TEST
API_URL_SAP = https://my419028-api.s4hana.cloud.sap
#API_URL_SAP = https://my418386-api.s4hana.cloud.sap

#IAS

USER_IAS = 2725d294-b703-4048-965b-7ae7715da0df
PASS_IAS = Uz0=VtJR23PF3@zIqZTXlxwJo_6iqk[:
URL_IAS =https://aakxwb17v.accounts.ondemand.com/
#------------------------------------------
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false