server.port=8080
# SETTING PORTAL
sm.portal.dev=false
#Comprador
sm.portal.nameId =P003490
sm.portal.nameDisplay =Comprador 1
sm.portal.email = mmonsalve@csticorp.biz
log.proceso.enabled = true

email.enabled = true
#Proveedor
sm.portal.prov.idSCP=P00005
sm.portal.prov.ruc=20101256422
sm.portal.prov.nameDisplay = Proveedor 1 DEEV
sm.portal.prov.email = coropeza@csticorp.biz

#CMIS CLOU FOUNDRY
#cmis.server=https://api-sdm-di.cfapps.us10.hana.ondemand.com/
#cmis.cliente.id=sb-64422fb6-b97b-42e3-a076-655d40a92161!b45995|sdm-di-DocumentManagement-sdm_integration!b6332
#cmis.cliente.secret=frCDf2xiTVJ9cB4OZBB2czBBgpk=
#cmis.repository.id=c1728054-7860-40e3-be3d-da935956747e
#cmis.server.credential=https://topytop-dev-jw3fh66g.authentication.us10.hana.ondemand.com
#
#QAS
cmis.server=https://api-sdm-di.cfapps.us10.hana.ondemand.com/
cmis.cliente.id=sb-ce0d83ef-d875-4bc9-bcc1-3d852ebb9a33!b345445|sdm-di-DocumentManagement-sdm_integration!b6332
cmis.cliente.secret=d32b0fa3-d9c2-4153-babe-4d26add3dfcd$vh88SkwXwn5rkEsMOBY5hUh5VJDtt8r9VLQb85Z6Yls=
cmis.repository.id=e34ae14a-982c-4060-b3d2-768aed020232
cmis.server.credential=https://jrc-dev-kgr01psw.authentication.us10.hana.ondemand.com

# CMIS
sm.portal.cmis.name = iproviderRepositoryQas
sm.portal.cmis.key = iproviderRepositoryQas
cfg.portal.cmis.name = iproviderRepositoryQas
cfg.portal.cmis.key = iproviderRepositoryQas
destination.cmis = IPROVIDER_CMIS

#Folder ECM
cfg.folder.ecm = ArchivosSunat

#ClaveSol
cfg.sunat.user = 20101045995PROVIDER
cfg.sunat.pass = Prov2021

#URL PORTAL
##CAMBIAR AQUI!!!
#sm.portal.url = https://flpnwc-a8vkr95ktt.dispatcher.br1.hana.ondemand.com/sites/iprovider#Shell-home
#DEV
#cfg.portal.url = https://centenariodev.cpp.cfapps.us10.hana.ondemand.com/portal/logoff.html?siteId=3748e5ff-9084-4723-a0be-7726388b50ba&sap-language=en
#QA
cfg.portal.url.centenario = https://jrc-dev-kgr01psw.launchpad.cfapps.us10.hana.ondemand.com/site?siteId=8760c77a-4e37-4018-a9b0-5be51fe91dec
cfg.portal.url = https://jrc-dev-kgr01psw.launchpad.cfapps.us10.hana.ondemand.com/site?siteId=8760c77a-4e37-4018-a9b0-5be51fe91dec

#PRD
#cfg.portal.url.centenario = https://centenarioprd.cpp.cfapps.us10.hana.ondemand.com/site?siteId=3748e5ff-9084-4723-a0be-7726388b50ba
#cfg.portal.url = https://centenario-prd-externo-2lpbif15.cpp.cfapps.us10.hana.ondemand.com/site?siteId=1fa6c73f-2453-4ed8-9f7c-b7e7c16db986

#cfg.portal.url = https://a2pyhjmjf.accounts.ondemand.com/saml2/idp/sso?sp=XSUAA_200e42b9-16e4-4145-8d44-322c90912330&RelayState=client_id%3D15697598-46e5-424d-aff2-f206c614f286%26response_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Fcentenarioqas.authentication.us10.hana.ondemand.com%252Flogin%252Fcallback%252Fsap.custom%26state%3DEHY4fDD4on%26scope%3Dopenid%2Bemail%26nonce%3DG7D2WEJwg5Se
cfg.portal.url.public.oc = https://flpnwc-f9iyf5gkk6.dispatcher.eu2.hana.ondemand.com/sites?siteId=3468528f-ff5a-4864-9f95-4f9874f1a34d&evictCache=true#iproviderpublicacionoccompras-Display


#WEBSERVICE PDF-XML COMPROBATE DE RETENCION
cfg.retencion.ws.url = http://qas.incloud.la:9998/services/S3getFilesCopeinca


#NOTIFICACIONES CONSULTAS URL
cfg.notificacion.consulta.url = noreplytpt@topitop.com.pe


# HANA (CLOUD) DB
# JPA / HIBERNATE
spring.jpa.properties.hibernate.format_sql=false
spring.datasource.driver-class-name=com.sap.db.jdbc.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.HANAColumnStoreDialect


spring.datasource.url = jdbc:sap://8bd71486-7b17-47d2-bd72-e2ce301cf1ad.hana.prod-us10.hanacloud.ondemand.com:443/?encrypt=true&ValidateCertificate=true
spring.datasource.username = IPROVIDER_DEV
spring.datasource.password = Pa$$w0rd


destination.email = SEND_MAIL_IREQUEST

# PRIMARY DATA SOURCE
# HANA (CLOUD) DB
# (= create, update, none)
spring.jpa.hibernate.ddl-auto = update
spring.jta.enabled = true
spring.jpa.show-sql = true

# Hikari will use the above plus the following to setup connection pooling
spring.datasource.hikari.minimumIdle=2
spring.datasource.hikari.maximumPoolSize=10
spring.datasource.hikari.idleTimeout=3000
spring.datasource.hikari.poolName=SpringBootJPAHikariCP
spring.datasource.hikari.maxLifetime=20000
spring.datasource.hikari.connectionTimeout=3000

#cambio
##### Propiedades para el Multipart File ####
spring.servlet.multipart.max-file-size =  2000MB
spring.servlet.multipart.max-request-size = 2000MB
server.tomcat.max-swallow-size=-1

#DESTINATIONS
#-----------------------------------------

#DEV? 300
destination.rfc.profit=SAP_IPROVIDER_CLONING

#QAS 520
#destination.rfc.profit=CFG_DEST_RFC_QAS_520

# Email (Desactivar el bloque si email.enabled esta en false)
spring.mail.default-encoding=UTF-8
spring.mail.host=smtp-mail.outlook.com
spring.mail.username=muqui@jrcing.com.pe
spring.mail.password=MJ$Ing08$
spring.mail.port=587

#------------------------------------------
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false