server.port=8080

# SETTING PORTAL
sm.portal.dev=true
sm.portal.nameId = 000000000
sm.portal.nameDisplay = Usuario Prueba
sm.portal.email = usuario@dominio.pe
log.proceso.enabled = true

#URL PORTAL
##CAMBIAR AQUI!!!
#sm.portal.url = https://flpnwc-a8vkr95ktt.dispatcher.br1.hana.ondemand.com/sites/iprovider#Shell-home
cfg.portal.url = https://dev-silvestre.cpp.cfapps.us10.hana.ondemand.com/site?siteId=94d16069-cf27-4ef4-a502-62577a3aaf6e#Shell-home

# CMIS
sm.portal.cmis.name = vendorRepositoryDev
sm.portal.cmis.key = vendorRepositoryDev
cfg.portal.cmis.name = iproviderRepositoryDev
cfg.portal.cmis.key = iproviderRepositoryDev
destination.cmis = IPROVIDER_CMIS

#Folder ECM
cfg.folder.ecm = ArchivosSunat

#ClaveSol
cfg.sunat.user = FESPINOZ
cfg.sunat.pass = fESPINOZA1

cfg.portal.url.public.oc = https://flpnwc-f9iyf5gkk6.dispatcher.eu2.hana.ondemand.com/sites?siteId=3468528f-ff5a-4864-9f95-4f9874f1a34d&evictCache=true#iproviderpublicacionoccompras-Display

#WEBSERVICE PDF-XML COMPROBATE DE RETENCION
cfg.retencion.ws.url = http://qas.incloud.la:9998/services/S3getFilesCopeinca

#NOTIFICACIONES CONSULTAS URL
cfg.notificacion.consulta.url = corptpt@topitop.com.pe

# HANA (CLOUD) DB
# JPA / HIBERNATE
spring.jpa.properties.hibernate.format_sql=false
spring.datasource.driver-class-name=com.sap.db.jdbc.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.HANAColumnStoreDialect


#spring.datasource.url = jdbc:sap://0349b274-e5fc-470d-a7a5-3bc38346f897.hana.prod-us10.hanacloud.ondemand.com:443/?user=IPROVIDER&currentSchema=IPROVIDER&password=Pa$$w0rd202102$$&encrypt=true&ValidateCertificate=true
#spring.datasource.username = IPROVIDER
#spring.datasource.password = Pa$$w0rd202102$$

spring.datasource.url = jdbc:sap://8bd71486-7b17-47d2-bd72-e2ce301cf1ad.hana.prod-us10.hanacloud.ondemand.com:443/?encrypt=true&ValidateCertificate=true
spring.datasource.username = IPROVIDER_DEV
spring.datasource.password = Pa$$w0rd
destination.email = SEND_MAIL_IREQUEST


# PRIMARY DATA SOURCE
# HANA (CLOUD) DB
spring.jpa.hibernate.ddl-auto = update
spring.jta.enabled = true
spring.jpa.show-sql = true

# Hikari will use the above plus the following to setup connection pooling
spring.datasource.hikari.minimumIdle=2
spring.datasource.hikari.maximumPoolSize=10
spring.datasource.hikari.idleTimeout=3000
spring.datasource.hikari.poolName=SpringBootJPAHikariCP
spring.datasource.hikari.maxLifetime=20000
spring.datasource.hikari.connectionTimeout=3000

#destinations
destination.rfc.profit=SF_DEST_RFC
spring.main.allow-bean-definition-overriding=true
