/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.incloud.hcp.repository;

import com.incloud.hcp.domain.EstadoProveedor;
import org.springframework.data.jpa.repository.JpaRepository;

public interface EstadoProveedorRepository extends JpaRepository<EstadoProveedor, Integer> {

    /**
     * Return the persistent instance of {@link EstadoProveedor} with the given unique property value descripcionEstadoProveedor,
     * or null if there is no such persistent instance.
     *
     * @param descripcionEstadoProveedor the unique value
     * @return the corresponding {@link EstadoProveedor} persistent instance or null
     */
    EstadoProveedor getByDescripcionEstadoProveedor(String descripcionEstadoProveedor);

    EstadoProveedor getByCodigoEstadoProveedor(String codigoEstadoProveedor);

}