/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.incloud.hcp.repository;

import com.incloud.hcp.domain.Indicador;
import org.springframework.data.jpa.repository.JpaRepository;

public interface IndicadorRepository extends JpaRepository<Indicador, Integer> {

    /**
     * Return the persistent instance of {@link Indicador} with the given unique property value descripcionIndicador,
     * or null if there is no such persistent instance.
     *
     * @param descripcionIndicador the unique value
     * @return the corresponding {@link Indicador} persistent instance or null
     */
    Indicador getByDescripcionIndicador(String descripcionIndicador);

    Indicador getIndicadorByCodigoTipoValorIndicador(String indicador);

}