/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.incloud.hcp.repository;

import com.incloud.hcp.domain.Licitacion;
import com.incloud.hcp.domain.LicitacionSubetapa;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;

import java.sql.Timestamp;
import java.util.Date;
import java.util.List;

public interface LicitacionSubetapaRepository extends JpaRepository<LicitacionSubetapa, Integer> {

    List<LicitacionSubetapa> findLicitacionSubetapaByIdLicitacionOrderByFechaCierreSubetapa(Licitacion licitacion);

    @Modifying
    @Query("DELETE FROM LicitacionSubetapa d WHERE d.idLicitacion.idLicitacion= ?1")
    void deleteDetailByLicitacion(Integer idLicitacion);

    @Query("SELECT max(u.fechaCierreSubetapa) from LicitacionSubetapa u where u.idLicitacion.idLicitacion =?1")
    Timestamp getMaxFechaCierreSubEtapaLicitacion(Integer idLicitacion);


    @Query("SELECT u from LicitacionSubetapa u where u.idLicitacion.estadoLicitacion = ?1 " +
            "and u.fechaEnvioCorreoRecordatorio is not null " +
            "and u.fechaEnvioCorreoRecordatorio < ?2 " +
            "and u.indEnviadoCorreoRecordatorio is null")
    List<LicitacionSubetapa> getListaEnviarCorreoRecordatorio(String estadoLicitacion, Date fecha);

    @Query("SELECT d FROM LicitacionSubetapa d WHERE d.idLicitacion.idLicitacion= ?1 and d.idSubetapa.indConfirmacionParticipacion = '1' ")
    List<LicitacionSubetapa> findByLicitacionConfirmacionParticipacion(Integer idLicitacion);

    @Query("SELECT d FROM LicitacionSubetapa d WHERE d.idLicitacion.idLicitacion= ?1 order by d.fechaCierreSubetapa asc ")
    LicitacionSubetapa findByLicitacion(Integer idLicitacion);


}