/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.incloud.hcp.repository;

import com.incloud.hcp.domain.MtrTipoDocumento;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import java.util.List;

public interface MtrTipoDocumentoRepository extends JpaRepository<MtrTipoDocumento, Integer> {

    MtrTipoDocumento findByCodigoTipoDocumento(String codigoDocumento);

    @Query(value =
            "SELECT p FROM MtrTipoDocumento p " +
                    "INNER JOIN  MtrAgrupadoTipoArchivo  ap ON p.mtrAgrupadoTipoArchivo.id = ap.id " +
                    "WHERE ap.codigoAgrupadoTipoArchivo  = ?1 " +
                    "ORDER BY p.descripcion ASC ")
    List<MtrTipoDocumento> getfindByCodigoAgrupado(String codigoAgrupadoArchivo);




    @Query(value =
            "SELECT p FROM MtrTipoDocumento p " +
                    "INNER JOIN  MtrAgrupadoTipoArchivo  ap ON p.mtrAgrupadoTipoArchivo.id = ap.id " +
                    "INNER JOIN  LineaComercial  lc ON p.lineaComercial.idLineaComercial = lc.idLineaComercial " +
                    "WHERE ap.codigoAgrupadoTipoArchivo  = ?1 " +
                    "AND lc.idLineaComercial  = ?2 " )
    List<MtrTipoDocumento> getfindByCodigoAgrupadoAndLineaComercial(String codigoAgrupadoArchivo,Integer idPadre);
}