/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.incloud.hcp.repository;

import com.incloud.hcp.domain.PreguntaInformacion;
import com.incloud.hcp.domain.PreguntaInformacionRespuesta;
import com.incloud.hcp.domain.ProveedorHomologacion;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import java.util.List;
import java.util.Optional;

public interface PreguntaInformacionRespuestaRepository extends JpaRepository<PreguntaInformacionRespuesta, Integer> {


    @Query("SELECT p FROM PreguntaInformacionRespuesta p WHERE p.idPreguntaInformacion.id = ?1")
    List<PreguntaInformacionRespuesta> consultarPreguntaInformacionRespuesta(Integer id);

}