/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.incloud.hcp.repository;

import com.incloud.hcp.domain.Proveedor;
import com.incloud.hcp.domain.ProveedorAdjuntoSunat;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;

import java.util.List;

public interface ProveedorAdjuntoSunatRepository extends JpaRepository<ProveedorAdjuntoSunat, Integer> {

    public List<ProveedorAdjuntoSunat> findByIdProveedorOrderByArchivoNombre(Proveedor proveedor);

    @Modifying
    @Query("delete from ProveedorAdjuntoSunat u where u.idProveedor.idProveedor = ?1 and u.archivoId = ?2")
     void deleteProveedorAdjuntoSunatByLicitacionandAndArchivoId(Integer idProveedor, String archivoId);

    @Modifying
    @Query("SELECT p FROM ProveedorAdjuntoSunat p WHERE p.idProveedor.idProveedor = ?1 and p.archivoTipo <> 'fichaDeDatos'")
    List<ProveedorAdjuntoSunat> getProveedorAdjuntoSunatByIdProveedor(Integer idProveedor);


    @Query("SELECT p FROM ProveedorAdjuntoSunat p WHERE p.idProveedor.idProveedor = ?1 and p.archivoTipo = ?2")
    List<ProveedorAdjuntoSunat> getProveedorAdjuntoSunatByIdProveedorAndArchivoTipo(Integer idProveedor,String archivoTipo);

    @Query("SELECT p FROM ProveedorAdjuntoSunat p WHERE p.idProveedor.idProveedor = ?1 and p.mtrTipoDocumento.codigoTipoDocumento = ?2")
    List<ProveedorAdjuntoSunat> getbyIdProveedorAndMtrTipoDocumento(Integer idProveedor,String codigoDocumento);

}