/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.incloud.hcp.repository;

import com.incloud.hcp.domain.Subetapa;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import java.util.List;

public interface SubetapaRepository extends JpaRepository<Subetapa, Integer> {


    /**
     * Return the persistent instance of {@link Subetapa} with the given unique property value descripcionSubetapa,
     * or null if there is no such persistent instance.
     *
     * @param descripcionSubetapa the unique value
     * @return the corresponding {@link Subetapa} persistent instance or null
     */
    Subetapa getByDescripcionSubetapa(String descripcionSubetapa);

    List<Subetapa> findByIndObligatorio(String indicador);
    List<Subetapa> findByIndRenegociacion(String indicador);

    @Query("select u from Subetapa u  order by u.orden")
    List<Subetapa> findAllSoloVisibles();
}