/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.incloud.hcp.repository;

import com.incloud.hcp.domain.TempBienServicio;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.query.Procedure;

public interface TempBienServicioRepository extends JpaRepository<TempBienServicio, Integer> {

    /**
     * Return the persistent instance of {@link TempBienServicio} with the given unique property value codigoSap,
     * or null if there is no such persistent instance.
     *
     * @param codigoSap the unique value
     * @return the corresponding {@link TempBienServicio} persistent instance or null
     */
    TempBienServicio getByCodigoSap(String codigoSap);

    @Procedure(name = "SP_MIGRACION_RFC_MATERIAL_SERVICIO")
    void saveNeworUpdateActualizados();

}