/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTOService.java.e.vm
 */
package com.incloud.hcp.service.impl;

import com.incloud.hcp.config.excel.ExcelDefault;
import com.incloud.hcp.domain.CotizacionAdjuntoRechazada;
import com.incloud.hcp.domain.CotizacionAdjuntoRechazada_;
import com.incloud.hcp.repository.CotizacionAdjuntoRechazadaRepository;
import com.incloud.hcp.repository.CotizacionRechazadaRepository;
import com.incloud.hcp.service.CotizacionAdjuntoRechazadaService;
import com.incloud.hcp.service.CotizacionRechazadaService;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.service.support.PageResponse;
import org.apache.commons.lang.StringUtils;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.DataFormat;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.streaming.SXSSFSheet;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.MessageSource;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.awt.*;
import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * A simple DTO Facility for CotizacionAdjuntoRechazada.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public abstract class CotizacionAdjuntoRechazadaServiceImpl implements CotizacionAdjuntoRechazadaService {

    protected final Logger log = LoggerFactory.getLogger(CotizacionAdjuntoRechazadaServiceImpl.class);

    protected final String NAME_SHEET = "CotizacionAdjuntoRechazada";
    protected final String CONFIG_TITLE = "com/incloud/hcp/excel/CotizacionAdjuntoRechazadaExcel.xml";

    @Autowired
    protected MessageSource messageSource;

    @Autowired
    protected CotizacionAdjuntoRechazadaRepository cotizacionAdjuntoRechazadaRepository;

    @Autowired
    protected CotizacionRechazadaService cotizacionRechazadaService;

    @Autowired
    protected CotizacionRechazadaRepository cotizacionRechazadaRepository;

    @Transactional(readOnly = true)
    public Optional<CotizacionAdjuntoRechazada> findOne(Integer id) {
        log.debug("Ingresando findOne: ", id);
        return this.cotizacionAdjuntoRechazadaRepository.findById(id);
    }

    @Transactional(readOnly = true)
    public List<CotizacionAdjuntoRechazada> findAll() {
        log.debug("Ingresando findAll");
        Sort sort = Sort.by("id");
        sort = this.setFindAll(sort);
        List<CotizacionAdjuntoRechazada> lista = this.cotizacionAdjuntoRechazadaRepository.findAll(sort);
        return lista;
    }

    protected abstract Sort setFindAll(Sort sort);

    @Transactional(readOnly = true)
    public List<CotizacionAdjuntoRechazada> find(CotizacionAdjuntoRechazada req) {
        log.debug("Ingresando find: ", req);
        Example<CotizacionAdjuntoRechazada> example = null;
        CotizacionAdjuntoRechazada cotizacionAdjuntoRechazada = req;
        ExampleMatcher matcher = null;
        if (cotizacionAdjuntoRechazada != null) {
            matcher = ExampleMatcher.matching() //
                    .withMatcher(CotizacionAdjuntoRechazada_.archivoId.getName(), match -> match.ignoreCase().startsWith())
                    .withMatcher(CotizacionAdjuntoRechazada_.archivoNombre.getName(), match -> match.ignoreCase().startsWith())
                    .withMatcher(CotizacionAdjuntoRechazada_.archivoTipo.getName(), match -> match.ignoreCase().startsWith())
                    .withMatcher(CotizacionAdjuntoRechazada_.descripcion.getName(), match -> match.ignoreCase().startsWith())
                    .withMatcher(CotizacionAdjuntoRechazada_.indCotizacion.getName(), match -> match.ignoreCase().startsWith())
                    .withMatcher(CotizacionAdjuntoRechazada_.rutaAdjunto.getName(), match -> match.ignoreCase().startsWith());
            example = Example.of(cotizacionAdjuntoRechazada, matcher);
        }
        Sort sort = Sort.by("id");
        sort = this.setFind(req, matcher, example, sort);
        List<CotizacionAdjuntoRechazada> lista = this.cotizacionAdjuntoRechazadaRepository.findAll(example, sort);
        return lista;
    }

    protected abstract Sort setFind(CotizacionAdjuntoRechazada req, ExampleMatcher matcher, Example<CotizacionAdjuntoRechazada> example, Sort sort);

    @Transactional(readOnly = true)
    public PageResponse<CotizacionAdjuntoRechazada> findPaginated(PageRequestByExample<CotizacionAdjuntoRechazada> req) {
        log.debug("Ingresando findPaginated: ", req);
        Example<CotizacionAdjuntoRechazada> example = null;
        CotizacionAdjuntoRechazada cotizacionAdjuntoRechazada = toEntity(req.example);
        ExampleMatcher matcher = null;
        if (cotizacionAdjuntoRechazada != null) {
            matcher = ExampleMatcher.matching() //
                    .withMatcher(CotizacionAdjuntoRechazada_.archivoId.getName(), match -> match.ignoreCase().startsWith())
                    .withMatcher(CotizacionAdjuntoRechazada_.archivoNombre.getName(), match -> match.ignoreCase().startsWith())
                    .withMatcher(CotizacionAdjuntoRechazada_.archivoTipo.getName(), match -> match.ignoreCase().startsWith())
                    .withMatcher(CotizacionAdjuntoRechazada_.descripcion.getName(), match -> match.ignoreCase().startsWith())
                    .withMatcher(CotizacionAdjuntoRechazada_.indCotizacion.getName(), match -> match.ignoreCase().startsWith())
                    .withMatcher(CotizacionAdjuntoRechazada_.rutaAdjunto.getName(), match -> match.ignoreCase().startsWith());
            example = Example.of(cotizacionAdjuntoRechazada, matcher);
        }

        Page<CotizacionAdjuntoRechazada> page;
        Sort sort = Sort.by("id");
        sort = this.setFind(cotizacionAdjuntoRechazada, matcher, example, sort);
        req.generarLazyDefecto();
        this.setFindPaginated(req, matcher, example);
        if (example != null) {
            page = this.cotizacionAdjuntoRechazadaRepository.findAll(example, req.toPageable(sort));
        } else {
            page = this.cotizacionAdjuntoRechazadaRepository.findAll(req.toPageable(sort));
        }

        List<CotizacionAdjuntoRechazada> content = page.getContent().stream().map(this::toDTO).collect(Collectors.toList());
        return new PageResponse<>(page.getTotalPages(), page.getTotalElements(), content);
    }

    protected abstract void setFindPaginated(PageRequestByExample<CotizacionAdjuntoRechazada> req, ExampleMatcher matcher,
            Example<CotizacionAdjuntoRechazada> example);

    @Transactional(readOnly = true)
    public XSSFWorkbook downloadExcelXLSX(CotizacionAdjuntoRechazada req) {
        log.debug("Ingresando downloadExcelXLSX: ", req);
        List<CotizacionAdjuntoRechazada> lista = this.find(req);
        Optional<List<CotizacionAdjuntoRechazada>> oList = Optional.ofNullable(lista);
        if (!oList.isPresent()) {
            return null;
        }

        XSSFWorkbook book = new XSSFWorkbook();
        XSSFSheet sheet = book.createSheet();
        int numberOfSheets = book.getNumberOfSheets();
        book.setSheetName(numberOfSheets - 1, NAME_SHEET);
        ExcelDefault.createTitle(sheet, CONFIG_TITLE, book.createCellStyle(), book.createFont());
        CellStyle cellStyle = book.createCellStyle();
        DataFormat dataFormat = book.createDataFormat();

        lista.forEach(cotizacionAdjuntoRechazada -> {
            int lastRow = sheet.getLastRowNum();
            int i = lastRow < 0 ? 0 : lastRow;
            XSSFRow dataRow = sheet.createRow(i + 1);
            int contador = 0;
            ExcelDefault.setValueCell(cotizacionAdjuntoRechazada.getId(), dataRow.createCell(contador), cellStyle, dataFormat);
            contador++;
            ExcelDefault.setValueCell(cotizacionAdjuntoRechazada.getArchivoId(), dataRow.createCell(contador), cellStyle, dataFormat);
            contador++;
            ExcelDefault.setValueCell(cotizacionAdjuntoRechazada.getArchivoNombre(), dataRow.createCell(contador), cellStyle, dataFormat);
            contador++;
            ExcelDefault.setValueCell(cotizacionAdjuntoRechazada.getArchivoTipo(), dataRow.createCell(contador), cellStyle, dataFormat);
            contador++;
            ExcelDefault.setValueCell(cotizacionAdjuntoRechazada.getDescripcion(), dataRow.createCell(contador), cellStyle, dataFormat);
            contador++;
            ExcelDefault.setValueCell(cotizacionAdjuntoRechazada.getIndCotizacion(), dataRow.createCell(contador), cellStyle, dataFormat);
            contador++;
            ExcelDefault.setValueCell(cotizacionAdjuntoRechazada.getRutaAdjunto(), dataRow.createCell(contador), cellStyle, dataFormat);
            contador++;
            /* Agregar aqui si desean colocar mas campos del BEAN */
            this.setDownloadExcelItem(cotizacionAdjuntoRechazada, dataRow);

        });
        this.setDownloadExcel(sheet);
        int totalColumn = sheet.getRow(0).getLastCellNum();
        for (int i = 0; i < totalColumn; i++) {
            sheet.autoSizeColumn(i, true);
        }
        return book;
    }

    protected void setDownloadExcelItem(CotizacionAdjuntoRechazada bean, XSSFRow dataRow) {

    }

    protected void setDownloadExcel(XSSFSheet sheet) {

    }

    @Transactional(readOnly = true)
    public SXSSFWorkbook downloadExcelSXLSX(CotizacionAdjuntoRechazada req) {
        log.debug("Ingresando downloadExcelSXLSX: ", req);
        List<CotizacionAdjuntoRechazada> lista = this.find(req);
        Optional<List<CotizacionAdjuntoRechazada>> oList = Optional.ofNullable(lista);
        if (!oList.isPresent()) {
            return null;
        }

        SXSSFWorkbook book = new SXSSFWorkbook(100);
        XSSFWorkbook xbook = book.getXSSFWorkbook();
        SXSSFSheet sheet = book.createSheet();
        sheet.trackAllColumnsForAutoSizing();
        int numberOfSheets = book.getNumberOfSheets();
        book.setSheetName(numberOfSheets - 1, NAME_SHEET);
        int nroColumnas = ExcelDefault.createTitle(xbook, sheet, CONFIG_TITLE);
        for (int i = 0; i < nroColumnas; i++) {
            sheet.autoSizeColumn(i, true);
        }
        sheet.untrackAllColumnsForAutoSizing();

        XSSFCellStyle cellStyle01 = ExcelDefault.devuelveCellStyle(xbook, new Color(0, 0, 1), new Color(226, 239, 218), false, (short) 10);
        XSSFCellStyle cellStyle02 = ExcelDefault.devuelveCellStyle(xbook, new Color(0, 0, 192), new Color(255, 255, 255), false, (short) 10);
        List<CellStyle> cellStyleList = null;
        List<CellStyle> cellStyleList01 = ExcelDefault.generarCellStyle(xbook, cellStyle01);
        List<CellStyle> cellStyleList02 = ExcelDefault.generarCellStyle(xbook, cellStyle02);
        boolean filaImpar = true;

        for (CotizacionAdjuntoRechazada cotizacionAdjuntoRechazada : lista) {
            int lastRow = sheet.getLastRowNum();
            int i = lastRow < 0 ? 0 : lastRow;
            Row dataRow = sheet.createRow(i + 1);
            int contador = 0;
            if (filaImpar) {
                cellStyleList = cellStyleList01;
            } else {
                cellStyleList = cellStyleList02;
            }
            filaImpar = !filaImpar;

            ExcelDefault.setValueCell(cotizacionAdjuntoRechazada.getId(), dataRow.createCell(contador), "I", cellStyleList);
            contador++;
            ExcelDefault.setValueCell(cotizacionAdjuntoRechazada.getArchivoId(), dataRow.createCell(contador), "S", cellStyleList);
            contador++;
            ExcelDefault.setValueCell(cotizacionAdjuntoRechazada.getArchivoNombre(), dataRow.createCell(contador), "S", cellStyleList);
            contador++;
            ExcelDefault.setValueCell(cotizacionAdjuntoRechazada.getArchivoTipo(), dataRow.createCell(contador), "S", cellStyleList);
            contador++;
            ExcelDefault.setValueCell(cotizacionAdjuntoRechazada.getDescripcion(), dataRow.createCell(contador), "S", cellStyleList);
            contador++;
            ExcelDefault.setValueCell(cotizacionAdjuntoRechazada.getIndCotizacion(), dataRow.createCell(contador), "S", cellStyleList);
            contador++;
            ExcelDefault.setValueCell(cotizacionAdjuntoRechazada.getRutaAdjunto(), dataRow.createCell(contador), "S", cellStyleList);
            contador++;
            /* Agregar aqui si desean colocar mas campos del BEAN */
            this.setDownloadExcelItem(cotizacionAdjuntoRechazada, dataRow);

        }
        this.setDownloadExcel(sheet);
        return book;
    }

    protected void setDownloadExcelItem(CotizacionAdjuntoRechazada bean, Row dataRow) {

    }

    protected void setDownloadExcel(Sheet sheet) {

    }

    @Transactional(readOnly = true)
    public SXSSFWorkbook generateInsertExcelSXLSX(CotizacionAdjuntoRechazada req) {
        log.debug("Ingresando generateInsertExcelSXLSX: ", req);
        List<CotizacionAdjuntoRechazada> lista = this.find(req);
        Optional<List<CotizacionAdjuntoRechazada>> oList = Optional.ofNullable(lista);
        if (!oList.isPresent()) {
            return null;
        }

        SXSSFWorkbook book = new SXSSFWorkbook(100);
        XSSFWorkbook xbook = book.getXSSFWorkbook();
        SXSSFSheet sheet = book.createSheet();
        sheet.trackAllColumnsForAutoSizing();
        int numberOfSheets = book.getNumberOfSheets();
        book.setSheetName(numberOfSheets - 1, NAME_SHEET);
        int nroColumnas = 1;
        for (int i = 0; i < nroColumnas; i++) {
            sheet.autoSizeColumn(i, true);
        }
        sheet.untrackAllColumnsForAutoSizing();
        XSSFCellStyle cellStyle01 = ExcelDefault.devuelveCellStyle(xbook, new Color(0, 0, 1), new Color(226, 239, 218), false, (short) 10);
        XSSFCellStyle cellStyle02 = ExcelDefault.devuelveCellStyle(xbook, new Color(0, 0, 192), new Color(255, 255, 255), false, (short) 10);
        List<CellStyle> cellStyleList = null;
        List<CellStyle> cellStyleList01 = ExcelDefault.generarCellStyle(xbook, cellStyle01);
        List<CellStyle> cellStyleList02 = ExcelDefault.generarCellStyle(xbook, cellStyle02);
        boolean filaImpar = true;

        for (CotizacionAdjuntoRechazada cotizacionAdjuntoRechazada : lista) {
            int lastRow = sheet.getLastRowNum();
            int i = lastRow < 0 ? 0 : lastRow;
            Row dataRow = sheet.createRow(i + 1);
            int contador = 0;
            if (filaImpar) {
                cellStyleList = cellStyleList01;
            } else {
                cellStyleList = cellStyleList02;
            }
            filaImpar = !filaImpar;
            String sqlInsert = "INSERT INTO cotizacion_adjunto_rechazada(";
            sqlInsert = sqlInsert + "id_cotizacion_adjunto_rechazada" + ", ";
            sqlInsert = sqlInsert + "archivo_id" + ", ";
            sqlInsert = sqlInsert + "archivo_nombre" + ", ";
            sqlInsert = sqlInsert + "archivo_tipo" + ", ";
            sqlInsert = sqlInsert + "descripcion" + ", ";
            sqlInsert = sqlInsert + "ind_cotizacion" + ", ";
            sqlInsert = sqlInsert + "ruta_adjunto" + ")";
            sqlInsert = sqlInsert + " VALUES (";
            sqlInsert = sqlInsert + cotizacionAdjuntoRechazada.getId() + ", ";
            if (StringUtils.isBlank(cotizacionAdjuntoRechazada.getArchivoId())) {
                sqlInsert = sqlInsert + "null" + ", ";
            } else {
                sqlInsert = sqlInsert + "'" + cotizacionAdjuntoRechazada.getArchivoId() + "'" + ", ";
            }
            if (StringUtils.isBlank(cotizacionAdjuntoRechazada.getArchivoNombre())) {
                sqlInsert = sqlInsert + "null" + ", ";
            } else {
                sqlInsert = sqlInsert + "'" + cotizacionAdjuntoRechazada.getArchivoNombre() + "'" + ", ";
            }
            if (StringUtils.isBlank(cotizacionAdjuntoRechazada.getArchivoTipo())) {
                sqlInsert = sqlInsert + "null" + ", ";
            } else {
                sqlInsert = sqlInsert + "'" + cotizacionAdjuntoRechazada.getArchivoTipo() + "'" + ", ";
            }
            if (StringUtils.isBlank(cotizacionAdjuntoRechazada.getDescripcion())) {
                sqlInsert = sqlInsert + "null" + ", ";
            } else {
                sqlInsert = sqlInsert + "'" + cotizacionAdjuntoRechazada.getDescripcion() + "'" + ", ";
            }
            if (StringUtils.isBlank(cotizacionAdjuntoRechazada.getIndCotizacion())) {
                sqlInsert = sqlInsert + "null" + ", ";
            } else {
                sqlInsert = sqlInsert + "'" + cotizacionAdjuntoRechazada.getIndCotizacion() + "'" + ", ";
            }
            if (StringUtils.isBlank(cotizacionAdjuntoRechazada.getRutaAdjunto())) {
                sqlInsert = sqlInsert + "null";
            } else {
                sqlInsert = sqlInsert + "'" + cotizacionAdjuntoRechazada.getRutaAdjunto() + "'";
            }
            sqlInsert = sqlInsert + " );";
            ExcelDefault.setValueCell(sqlInsert, dataRow.createCell(contador), "S", cellStyleList);
            contador++;
        }
        return book;
    }

    protected CotizacionAdjuntoRechazada completarDatosBean(CotizacionAdjuntoRechazada bean) {
        BigDecimal data = new BigDecimal(0.00);
        bean = this.setCompletarDatosBean(bean);
        return bean;
    }

    protected CotizacionAdjuntoRechazada setCompletarDatosBean(CotizacionAdjuntoRechazada bean) {
        return bean;
    }

    /**
     * Save the passed dto as a new entity or update the corresponding entity if any.
     */
    public CotizacionAdjuntoRechazada save(CotizacionAdjuntoRechazada dto) {
        log.debug("Ingresando save: ", dto);
        if (dto == null) {
            return null;
        }
        dto = this.completarDatosBean(dto);
        dto = this.setBeforeSave(dto);
        this.setSave(dto);
        dto = this.cotizacionAdjuntoRechazadaRepository.save(dto);
        dto = this.setAfterSave(dto);
        return dto;
    }

    protected abstract void setSave(CotizacionAdjuntoRechazada dto);

    protected CotizacionAdjuntoRechazada setBeforeSave(CotizacionAdjuntoRechazada dto) {
        return dto;
    }

    protected CotizacionAdjuntoRechazada setAfterSave(CotizacionAdjuntoRechazada dto) {
        return dto;
    }

    /**
    * Save new entity or update the corresponding entity if any.
    */
    public CotizacionAdjuntoRechazada create(CotizacionAdjuntoRechazada dto) {
        log.debug("Ingresando create: ", dto);
        if (dto == null) {
            return null;
        }

        CotizacionAdjuntoRechazada cotizacionAdjuntoRechazada;
        cotizacionAdjuntoRechazada = new CotizacionAdjuntoRechazada();

        cotizacionAdjuntoRechazada.setArchivoId(dto.getArchivoId());
        cotizacionAdjuntoRechazada.setArchivoNombre(dto.getArchivoNombre());
        cotizacionAdjuntoRechazada.setArchivoTipo(dto.getArchivoTipo());
        cotizacionAdjuntoRechazada.setDescripcion(dto.getDescripcion());
        cotizacionAdjuntoRechazada.setIndCotizacion(dto.getIndCotizacion());
        cotizacionAdjuntoRechazada.setRutaAdjunto(dto.getRutaAdjunto());
        cotizacionAdjuntoRechazada = this.completarDatosBean(cotizacionAdjuntoRechazada);
        this.setCreate(cotizacionAdjuntoRechazada);
        return this.cotizacionAdjuntoRechazadaRepository.save(cotizacionAdjuntoRechazada);
    }

    protected abstract void setCreate(CotizacionAdjuntoRechazada dto);

    protected String validacionesPrevias(CotizacionAdjuntoRechazada dto) {
        return "";
    }

    /**
     * Delete the passed dto as a new entity or update the corresponding entity if any.
     */
    public void delete(Integer id) {
        log.debug("Ingresando delete: ", id);
        if (id == null) {
            return;
        }
        this.setDelete(id);
        this.cotizacionAdjuntoRechazadaRepository.deleteById(id);
    }

    protected abstract void setDelete(Integer id);

    public void deleteAll() {
        log.debug("Ingresando deleteAll");
        this.setDeleteAll();
        this.cotizacionAdjuntoRechazadaRepository.deleteAll();
    }

    protected abstract void setDeleteAll();

    /**
     * Converts the passed cotizacionAdjuntoRechazada to a DTO.
     */
    protected CotizacionAdjuntoRechazada toDTO(CotizacionAdjuntoRechazada cotizacionAdjuntoRechazada) {
        return cotizacionAdjuntoRechazada;
    }

    /**
     * Converts the passed dto to a CotizacionAdjuntoRechazada.
     * Convenient for query by example.
     */
    protected CotizacionAdjuntoRechazada toEntity(CotizacionAdjuntoRechazada dto) {
        return dto;
    }

}