/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTOService.java.e.vm
 */
package com.incloud.hcp.service.impl;

import com.incloud.hcp.config.excel.ExcelDefault;
import com.incloud.hcp.domain.LicitacionSubetapa;
import com.incloud.hcp.repository.LicitacionRepository;
import com.incloud.hcp.repository.LicitacionSubetapaRepository;
import com.incloud.hcp.repository.SubetapaRepository;
import com.incloud.hcp.service.LicitacionService;
import com.incloud.hcp.service.LicitacionSubetapaService;
import com.incloud.hcp.service._framework.BaseServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.service.support.PageResponse;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.DataFormat;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.streaming.SXSSFSheet;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.MessageSource;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.awt.*;
import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * A simple DTO Facility for LicitacionSubetapa.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public abstract class LicitacionSubetapaServiceImpl extends BaseServiceImpl implements LicitacionSubetapaService {

    protected final Logger log = LoggerFactory.getLogger(LicitacionSubetapaServiceImpl.class);

    protected final String NAME_SHEET = "LicitacionSubetapa";
    protected final String CONFIG_TITLE = "com/incloud/hcp/excel/LicitacionSubetapaExcel.xml";

    @Autowired
    protected MessageSource messageSource;

    @Autowired
    protected LicitacionSubetapaRepository licitacionSubetapaRepository;


    @Autowired
    protected SubetapaRepository subetapaRepository;

    @Autowired
    protected LicitacionService licitacionService;

    @Autowired
    protected LicitacionRepository licitacionRepository;

    @Transactional(readOnly = true)
    public Optional<LicitacionSubetapa> findOne(Integer id) {
        log.debug("Ingresando findOne: ", id);
        return this.licitacionSubetapaRepository.findById(id);
    }

    @Transactional(readOnly = true)
    public List<LicitacionSubetapa> findAll() {
        log.debug("Ingresando findAll");
        Sort sort = Sort.by("id");
        sort = this.setFindAll(sort);
        List<LicitacionSubetapa> lista = this.licitacionSubetapaRepository.findAll(sort);
        return lista;
    }

    protected abstract Sort setFindAll(Sort sort);

    @Transactional(readOnly = true)
    public List<LicitacionSubetapa> find(LicitacionSubetapa req) {
        log.debug("Ingresando find: ", req);
        Example<LicitacionSubetapa> example = null;
        LicitacionSubetapa licitacionSubetapa = req;
        ExampleMatcher matcher = null;
        if (licitacionSubetapa != null) {
            matcher = ExampleMatcher.matching() //
            ;
            example = Example.of(licitacionSubetapa, matcher);
        }
        Sort sort = Sort.by("id");
        sort = this.setFind(req, matcher, example, sort);
        List<LicitacionSubetapa> lista = this.licitacionSubetapaRepository.findAll(example, sort);
        return lista;
    }

    protected abstract Sort setFind(LicitacionSubetapa req, ExampleMatcher matcher, Example<LicitacionSubetapa> example, Sort sort);

    @Transactional(readOnly = true)
    public PageResponse<LicitacionSubetapa> findPaginated(PageRequestByExample<LicitacionSubetapa> req) {
        log.debug("Ingresando findPaginated: ", req);
        Example<LicitacionSubetapa> example = null;
        LicitacionSubetapa licitacionSubetapa = toEntity(req.example);
        ExampleMatcher matcher = null;
        if (licitacionSubetapa != null) {
            matcher = ExampleMatcher.matching() //
            ;
            example = Example.of(licitacionSubetapa, matcher);
        }

        Page<LicitacionSubetapa> page;
        Sort sort = Sort.by("id");
        sort = this.setFind(licitacionSubetapa, matcher, example, sort);
        req.generarLazyDefecto();
        this.setFindPaginated(req, matcher, example);
        if (example != null) {
            page = this.licitacionSubetapaRepository.findAll(example, req.toPageable(sort));
        } else {
            page = this.licitacionSubetapaRepository.findAll(req.toPageable(sort));
        }

        List<LicitacionSubetapa> content = page.getContent().stream().map(this::toDTO).collect(Collectors.toList());
        return new PageResponse<>(page.getTotalPages(), page.getTotalElements(), content);
    }

    protected abstract void setFindPaginated(PageRequestByExample<LicitacionSubetapa> req, ExampleMatcher matcher, Example<LicitacionSubetapa> example);

    @Transactional(readOnly = true)
    public XSSFWorkbook downloadExcelXLSX(LicitacionSubetapa req) {
        log.debug("Ingresando downloadExcelXLSX: ", req);
        List<LicitacionSubetapa> lista = this.find(req);
        Optional<List<LicitacionSubetapa>> oList = Optional.ofNullable(lista);
        if (!oList.isPresent()) {
            return null;
        }

        XSSFWorkbook book = new XSSFWorkbook();
        XSSFSheet sheet = book.createSheet();
        int numberOfSheets = book.getNumberOfSheets();
        book.setSheetName(numberOfSheets - 1, NAME_SHEET);
        ExcelDefault.createTitle(sheet, CONFIG_TITLE, book.createCellStyle(), book.createFont());
        CellStyle cellStyle = book.createCellStyle();
        DataFormat dataFormat = book.createDataFormat();

        lista.forEach(licitacionSubetapa -> {
            int lastRow = sheet.getLastRowNum();
            int i = lastRow < 0 ? 0 : lastRow;
            XSSFRow dataRow = sheet.createRow(i + 1);
            int contador = 0;
            ExcelDefault.setValueCell(licitacionSubetapa.getId(), dataRow.createCell(contador), cellStyle, dataFormat);
            contador++;
            ExcelDefault.setValueCell(licitacionSubetapa.getFechaCierreSubetapa(), dataRow.createCell(contador), cellStyle, dataFormat);
            contador++;
            ExcelDefault.setValueCell(licitacionSubetapa.getFechaEnvioCorreoRecordatorio(), dataRow.createCell(contador), cellStyle, dataFormat);
            contador++;
            /* Agregar aqui si desean colocar mas campos del BEAN */
            this.setDownloadExcelItem(licitacionSubetapa, dataRow);

        });
        this.setDownloadExcel(sheet);
        int totalColumn = sheet.getRow(0).getLastCellNum();
        for (int i = 0; i < totalColumn; i++) {
            sheet.autoSizeColumn(i, true);
        }
        return book;
    }

    protected void setDownloadExcelItem(LicitacionSubetapa bean, XSSFRow dataRow) {

    }

    protected void setDownloadExcel(XSSFSheet sheet) {

    }

    @Transactional(readOnly = true)
    public SXSSFWorkbook downloadExcelSXLSX(LicitacionSubetapa req) {
        log.debug("Ingresando downloadExcelSXLSX: ", req);
        List<LicitacionSubetapa> lista = this.find(req);
        Optional<List<LicitacionSubetapa>> oList = Optional.ofNullable(lista);
        if (!oList.isPresent()) {
            return null;
        }

        SXSSFWorkbook book = new SXSSFWorkbook(100);
        XSSFWorkbook xbook = book.getXSSFWorkbook();
        SXSSFSheet sheet = book.createSheet();
        sheet.trackAllColumnsForAutoSizing();
        int numberOfSheets = book.getNumberOfSheets();
        book.setSheetName(numberOfSheets - 1, NAME_SHEET);
        int nroColumnas = ExcelDefault.createTitle(xbook, sheet, CONFIG_TITLE);
        for (int i = 0; i < nroColumnas; i++) {
            sheet.autoSizeColumn(i, true);
        }
        sheet.untrackAllColumnsForAutoSizing();

        XSSFCellStyle cellStyle01 = ExcelDefault.devuelveCellStyle(xbook, new Color(0, 0, 1), new Color(226, 239, 218), false, (short) 10);
        XSSFCellStyle cellStyle02 = ExcelDefault.devuelveCellStyle(xbook, new Color(0, 0, 192), new Color(255, 255, 255), false, (short) 10);
        List<CellStyle> cellStyleList = null;
        List<CellStyle> cellStyleList01 = ExcelDefault.generarCellStyle(xbook, cellStyle01);
        List<CellStyle> cellStyleList02 = ExcelDefault.generarCellStyle(xbook, cellStyle02);
        boolean filaImpar = true;

        for (LicitacionSubetapa licitacionSubetapa : lista) {
            int lastRow = sheet.getLastRowNum();
            int i = lastRow < 0 ? 0 : lastRow;
            Row dataRow = sheet.createRow(i + 1);
            int contador = 0;
            if (filaImpar) {
                cellStyleList = cellStyleList01;
            } else {
                cellStyleList = cellStyleList02;
            }
            filaImpar = !filaImpar;

            ExcelDefault.setValueCell(licitacionSubetapa.getId(), dataRow.createCell(contador), "I", cellStyleList);
            contador++;
            ExcelDefault.setValueCell(licitacionSubetapa.getFechaCierreSubetapa(), dataRow.createCell(contador), "DT", cellStyleList);
            contador++;
            ExcelDefault.setValueCell(licitacionSubetapa.getFechaEnvioCorreoRecordatorio(), dataRow.createCell(contador), "DT", cellStyleList);
            contador++;
            /* Agregar aqui si desean colocar mas campos del BEAN */
            this.setDownloadExcelItem(licitacionSubetapa, dataRow);

        }
        this.setDownloadExcel(sheet);
        return book;
    }

    protected void setDownloadExcelItem(LicitacionSubetapa bean, Row dataRow) {

    }

    protected void setDownloadExcel(Sheet sheet) {

    }

    @Transactional(readOnly = true)
    public SXSSFWorkbook generateInsertExcelSXLSX(LicitacionSubetapa req) {
        log.debug("Ingresando generateInsertExcelSXLSX: ", req);
        List<LicitacionSubetapa> lista = this.find(req);
        Optional<List<LicitacionSubetapa>> oList = Optional.ofNullable(lista);
        if (!oList.isPresent()) {
            return null;
        }

        SXSSFWorkbook book = new SXSSFWorkbook(100);
        XSSFWorkbook xbook = book.getXSSFWorkbook();
        SXSSFSheet sheet = book.createSheet();
        sheet.trackAllColumnsForAutoSizing();
        int numberOfSheets = book.getNumberOfSheets();
        book.setSheetName(numberOfSheets - 1, NAME_SHEET);
        int nroColumnas = 1;
        for (int i = 0; i < nroColumnas; i++) {
            sheet.autoSizeColumn(i, true);
        }
        sheet.untrackAllColumnsForAutoSizing();
        XSSFCellStyle cellStyle01 = ExcelDefault.devuelveCellStyle(xbook, new Color(0, 0, 1), new Color(226, 239, 218), false, (short) 10);
        XSSFCellStyle cellStyle02 = ExcelDefault.devuelveCellStyle(xbook, new Color(0, 0, 192), new Color(255, 255, 255), false, (short) 10);
        List<CellStyle> cellStyleList = null;
        List<CellStyle> cellStyleList01 = ExcelDefault.generarCellStyle(xbook, cellStyle01);
        List<CellStyle> cellStyleList02 = ExcelDefault.generarCellStyle(xbook, cellStyle02);
        boolean filaImpar = true;

        for (LicitacionSubetapa licitacionSubetapa : lista) {
            int lastRow = sheet.getLastRowNum();
            int i = lastRow < 0 ? 0 : lastRow;
            Row dataRow = sheet.createRow(i + 1);
            int contador = 0;
            if (filaImpar) {
                cellStyleList = cellStyleList01;
            } else {
                cellStyleList = cellStyleList02;
            }
            filaImpar = !filaImpar;
            String sqlInsert = "INSERT INTO licitacion_subetapa(";
            sqlInsert = sqlInsert + "id_licitacion_subestapa" + ", ";
            sqlInsert = sqlInsert + "fecha_cierre_subetapa" + ", ";
            sqlInsert = sqlInsert + "fecha_envio_correo_recordatorio" + ")";
            sqlInsert = sqlInsert + " VALUES (";
            sqlInsert = sqlInsert + licitacionSubetapa.getId() + ", ";
            if (Optional.ofNullable(licitacionSubetapa.getFechaCierreSubetapa()).isPresent()) {
                sqlInsert = sqlInsert + licitacionSubetapa.getFechaCierreSubetapa().getTime() + ", ";
            }

            else {
                sqlInsert = sqlInsert + "null" + ", ";
            }
            if (Optional.ofNullable(licitacionSubetapa.getFechaEnvioCorreoRecordatorio()).isPresent()) {
                sqlInsert = sqlInsert + licitacionSubetapa.getFechaEnvioCorreoRecordatorio().getTime();
            }

            else {
                sqlInsert = sqlInsert + "null";
            }
            sqlInsert = sqlInsert + " );";
            ExcelDefault.setValueCell(sqlInsert, dataRow.createCell(contador), "S", cellStyleList);
            contador++;
        }
        return book;
    }

    protected LicitacionSubetapa completarDatosBean(LicitacionSubetapa bean) {
        BigDecimal data = new BigDecimal(0.00);
        bean = this.setCompletarDatosBean(bean);
        return bean;
    }

    protected LicitacionSubetapa setCompletarDatosBean(LicitacionSubetapa bean) {
        return bean;
    }

    /**
     * Save the passed dto as a new entity or update the corresponding entity if any.
     */
    public LicitacionSubetapa save(LicitacionSubetapa dto) {
        log.debug("Ingresando save: ", dto);
        if (dto == null) {
            return null;
        }
        dto = this.completarDatosBean(dto);
        dto = this.setBeforeSave(dto);
        this.setSave(dto);
        dto = this.licitacionSubetapaRepository.save(dto);
        dto = this.setAfterSave(dto);
        return dto;
    }

    protected abstract void setSave(LicitacionSubetapa dto);

    protected LicitacionSubetapa setBeforeSave(LicitacionSubetapa dto) {
        return dto;
    }

    protected LicitacionSubetapa setAfterSave(LicitacionSubetapa dto) {
        return dto;
    }

    /**
    * Save new entity or update the corresponding entity if any.
    */
    public LicitacionSubetapa create(LicitacionSubetapa dto) {
        log.debug("Ingresando create: ", dto);
        if (dto == null) {
            return null;
        }

        LicitacionSubetapa licitacionSubetapa;
        licitacionSubetapa = new LicitacionSubetapa();

        licitacionSubetapa.setFechaCierreSubetapa(dto.getFechaCierreSubetapa());
        licitacionSubetapa.setFechaEnvioCorreoRecordatorio(dto.getFechaEnvioCorreoRecordatorio());
        licitacionSubetapa = this.completarDatosBean(licitacionSubetapa);
        this.setCreate(licitacionSubetapa);
        return this.licitacionSubetapaRepository.save(licitacionSubetapa);
    }

    protected abstract void setCreate(LicitacionSubetapa dto);

    protected String validacionesPrevias(LicitacionSubetapa dto) {
        return "";
    }

    /**
     * Delete the passed dto as a new entity or update the corresponding entity if any.
     */
    public void delete(Integer id) {
        log.debug("Ingresando delete: ", id);
        if (id == null) {
            return;
        }
        this.setDelete(id);
        this.licitacionSubetapaRepository.deleteById(id);
    }

    protected abstract void setDelete(Integer id);

    public void deleteAll() {
        log.debug("Ingresando deleteAll");
        this.setDeleteAll();
        this.licitacionSubetapaRepository.deleteAll();
    }

    protected abstract void setDeleteAll();

    /**
     * Converts the passed licitacionSubetapa to a DTO.
     */
    protected LicitacionSubetapa toDTO(LicitacionSubetapa licitacionSubetapa) {
        return licitacionSubetapa;
    }

    /**
     * Converts the passed dto to a LicitacionSubetapa.
     * Convenient for query by example.
     */
    protected LicitacionSubetapa toEntity(LicitacionSubetapa dto) {
        return dto;
    }

}