/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTOService.java.e.vm
 */
package com.incloud.hcp.service.impl;

import com.incloud.hcp.config.excel.ExcelDefault;
import com.incloud.hcp.domain.PreRegistroLineaComercial;
import com.incloud.hcp.repository.LineaComercialRepository;
import com.incloud.hcp.repository.PreRegistroLineaComercialRepository;
import com.incloud.hcp.repository.PreRegistroProveedorRepository;
import com.incloud.hcp.service.LineaComercialService;
import com.incloud.hcp.service.PreRegistroLineaComercialService;
import com.incloud.hcp.service.PreRegistroProveedorService;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.service.support.PageResponse;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.DataFormat;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.streaming.SXSSFSheet;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.MessageSource;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.awt.*;
import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * A simple DTO Facility for PreRegistroLineaComercial.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public abstract class PreRegistroLineaComercialServiceImpl implements PreRegistroLineaComercialService {

    protected final Logger log = LoggerFactory.getLogger(PreRegistroLineaComercialServiceImpl.class);

    protected final String NAME_SHEET = "PreRegistroLineaComercial";
    protected final String CONFIG_TITLE = "com/incloud/hcp/excel/PreRegistroLineaComercialExcel.xml";

    @Autowired
    protected MessageSource messageSource;

    @Autowired
    protected PreRegistroLineaComercialRepository preRegistroLineaComercialRepository;

    @Autowired
    protected LineaComercialService lineaComercialService;

    @Autowired
    protected LineaComercialRepository lineaComercialRepository;

    @Autowired
    protected PreRegistroProveedorService preRegistroProveedorService;

    @Autowired
    protected PreRegistroProveedorRepository preRegistroProveedorRepository;

    @Transactional(readOnly = true)
    public Optional<PreRegistroLineaComercial> findOne(Integer id) {
        log.debug("Ingresando findOne: ", id);
        return this.preRegistroLineaComercialRepository.findById(id);
    }

    @Transactional(readOnly = true)
    public List<PreRegistroLineaComercial> findAll() {
        log.debug("Ingresando findAll");
        Sort sort = Sort.by("id");
        sort = this.setFindAll(sort);
        List<PreRegistroLineaComercial> lista = this.preRegistroLineaComercialRepository.findAll(sort);
        return lista;
    }

    protected abstract Sort setFindAll(Sort sort);

    @Transactional(readOnly = true)
    public List<PreRegistroLineaComercial> find(PreRegistroLineaComercial req) {
        log.debug("Ingresando find: ", req);
        Example<PreRegistroLineaComercial> example = null;
        PreRegistroLineaComercial preRegistroLineaComercial = req;
        ExampleMatcher matcher = null;
        if (preRegistroLineaComercial != null) {
            matcher = ExampleMatcher.matching() //
            ;
            example = Example.of(preRegistroLineaComercial, matcher);
        }
        Sort sort = Sort.by("id");
        sort = this.setFind(req, matcher, example, sort);
        List<PreRegistroLineaComercial> lista = this.preRegistroLineaComercialRepository.findAll(example, sort);
        return lista;
    }

    protected abstract Sort setFind(PreRegistroLineaComercial req, ExampleMatcher matcher, Example<PreRegistroLineaComercial> example, Sort sort);

    @Transactional(readOnly = true)
    public PageResponse<PreRegistroLineaComercial> findPaginated(PageRequestByExample<PreRegistroLineaComercial> req) {
        log.debug("Ingresando findPaginated: ", req);
        Example<PreRegistroLineaComercial> example = null;
        PreRegistroLineaComercial preRegistroLineaComercial = toEntity(req.example);
        ExampleMatcher matcher = null;
        if (preRegistroLineaComercial != null) {
            matcher = ExampleMatcher.matching() //
            ;
            example = Example.of(preRegistroLineaComercial, matcher);
        }

        Page<PreRegistroLineaComercial> page;
        Sort sort = Sort.by("id");
        sort = this.setFind(preRegistroLineaComercial, matcher, example, sort);
        req.generarLazyDefecto();
        this.setFindPaginated(req, matcher, example);
        if (example != null) {
            page = this.preRegistroLineaComercialRepository.findAll(example, req.toPageable(sort));
        } else {
            page = this.preRegistroLineaComercialRepository.findAll(req.toPageable(sort));
        }

        List<PreRegistroLineaComercial> content = page.getContent().stream().map(this::toDTO).collect(Collectors.toList());
        return new PageResponse<>(page.getTotalPages(), page.getTotalElements(), content);
    }

    protected abstract void setFindPaginated(PageRequestByExample<PreRegistroLineaComercial> req, ExampleMatcher matcher,
            Example<PreRegistroLineaComercial> example);

    @Transactional(readOnly = true)
    public XSSFWorkbook downloadExcelXLSX(PreRegistroLineaComercial req) {
        log.debug("Ingresando downloadExcelXLSX: ", req);
        List<PreRegistroLineaComercial> lista = this.find(req);
        Optional<List<PreRegistroLineaComercial>> oList = Optional.ofNullable(lista);
        if (!oList.isPresent()) {
            return null;
        }

        XSSFWorkbook book = new XSSFWorkbook();
        XSSFSheet sheet = book.createSheet();
        int numberOfSheets = book.getNumberOfSheets();
        book.setSheetName(numberOfSheets - 1, NAME_SHEET);
        ExcelDefault.createTitle(sheet, CONFIG_TITLE, book.createCellStyle(), book.createFont());
        CellStyle cellStyle = book.createCellStyle();
        DataFormat dataFormat = book.createDataFormat();

        lista.forEach(preRegistroLineaComercial -> {
            int lastRow = sheet.getLastRowNum();
            int i = lastRow < 0 ? 0 : lastRow;
            XSSFRow dataRow = sheet.createRow(i + 1);
            int contador = 0;
            ExcelDefault.setValueCell(preRegistroLineaComercial.getId(), dataRow.createCell(contador), cellStyle, dataFormat);
            contador++;
            /* Agregar aqui si desean colocar mas campos del BEAN */
            this.setDownloadExcelItem(preRegistroLineaComercial, dataRow);

        });
        this.setDownloadExcel(sheet);
        int totalColumn = sheet.getRow(0).getLastCellNum();
        for (int i = 0; i < totalColumn; i++) {
            sheet.autoSizeColumn(i, true);
        }
        return book;
    }

    protected void setDownloadExcelItem(PreRegistroLineaComercial bean, XSSFRow dataRow) {

    }

    protected void setDownloadExcel(XSSFSheet sheet) {

    }

    @Transactional(readOnly = true)
    public SXSSFWorkbook downloadExcelSXLSX(PreRegistroLineaComercial req) {
        log.debug("Ingresando downloadExcelSXLSX: ", req);
        List<PreRegistroLineaComercial> lista = this.find(req);
        Optional<List<PreRegistroLineaComercial>> oList = Optional.ofNullable(lista);
        if (!oList.isPresent()) {
            return null;
        }

        SXSSFWorkbook book = new SXSSFWorkbook(100);
        XSSFWorkbook xbook = book.getXSSFWorkbook();
        SXSSFSheet sheet = book.createSheet();
        sheet.trackAllColumnsForAutoSizing();
        int numberOfSheets = book.getNumberOfSheets();
        book.setSheetName(numberOfSheets - 1, NAME_SHEET);
        int nroColumnas = ExcelDefault.createTitle(xbook, sheet, CONFIG_TITLE);
        for (int i = 0; i < nroColumnas; i++) {
            sheet.autoSizeColumn(i, true);
        }
        sheet.untrackAllColumnsForAutoSizing();

        XSSFCellStyle cellStyle01 = ExcelDefault.devuelveCellStyle(xbook, new Color(0, 0, 1), new Color(226, 239, 218), false, (short) 10);
        XSSFCellStyle cellStyle02 = ExcelDefault.devuelveCellStyle(xbook, new Color(0, 0, 192), new Color(255, 255, 255), false, (short) 10);
        List<CellStyle> cellStyleList = null;
        List<CellStyle> cellStyleList01 = ExcelDefault.generarCellStyle(xbook, cellStyle01);
        List<CellStyle> cellStyleList02 = ExcelDefault.generarCellStyle(xbook, cellStyle02);
        boolean filaImpar = true;

        for (PreRegistroLineaComercial preRegistroLineaComercial : lista) {
            int lastRow = sheet.getLastRowNum();
            int i = lastRow < 0 ? 0 : lastRow;
            Row dataRow = sheet.createRow(i + 1);
            int contador = 0;
            if (filaImpar) {
                cellStyleList = cellStyleList01;
            } else {
                cellStyleList = cellStyleList02;
            }
            filaImpar = !filaImpar;

            ExcelDefault.setValueCell(preRegistroLineaComercial.getId(), dataRow.createCell(contador), "I", cellStyleList);
            contador++;
            /* Agregar aqui si desean colocar mas campos del BEAN */
            this.setDownloadExcelItem(preRegistroLineaComercial, dataRow);

        }
        this.setDownloadExcel(sheet);
        return book;
    }

    protected void setDownloadExcelItem(PreRegistroLineaComercial bean, Row dataRow) {

    }

    protected void setDownloadExcel(Sheet sheet) {

    }

    @Transactional(readOnly = true)
    public SXSSFWorkbook generateInsertExcelSXLSX(PreRegistroLineaComercial req) {
        log.debug("Ingresando generateInsertExcelSXLSX: ", req);
        List<PreRegistroLineaComercial> lista = this.find(req);
        Optional<List<PreRegistroLineaComercial>> oList = Optional.ofNullable(lista);
        if (!oList.isPresent()) {
            return null;
        }

        SXSSFWorkbook book = new SXSSFWorkbook(100);
        XSSFWorkbook xbook = book.getXSSFWorkbook();
        SXSSFSheet sheet = book.createSheet();
        sheet.trackAllColumnsForAutoSizing();
        int numberOfSheets = book.getNumberOfSheets();
        book.setSheetName(numberOfSheets - 1, NAME_SHEET);
        int nroColumnas = 1;
        for (int i = 0; i < nroColumnas; i++) {
            sheet.autoSizeColumn(i, true);
        }
        sheet.untrackAllColumnsForAutoSizing();
        XSSFCellStyle cellStyle01 = ExcelDefault.devuelveCellStyle(xbook, new Color(0, 0, 1), new Color(226, 239, 218), false, (short) 10);
        XSSFCellStyle cellStyle02 = ExcelDefault.devuelveCellStyle(xbook, new Color(0, 0, 192), new Color(255, 255, 255), false, (short) 10);
        List<CellStyle> cellStyleList = null;
        List<CellStyle> cellStyleList01 = ExcelDefault.generarCellStyle(xbook, cellStyle01);
        List<CellStyle> cellStyleList02 = ExcelDefault.generarCellStyle(xbook, cellStyle02);
        boolean filaImpar = true;

        for (PreRegistroLineaComercial preRegistroLineaComercial : lista) {
            int lastRow = sheet.getLastRowNum();
            int i = lastRow < 0 ? 0 : lastRow;
            Row dataRow = sheet.createRow(i + 1);
            int contador = 0;
            if (filaImpar) {
                cellStyleList = cellStyleList01;
            } else {
                cellStyleList = cellStyleList02;
            }
            filaImpar = !filaImpar;
            String sqlInsert = "INSERT INTO pre_registro_linea_comercial(";
            sqlInsert = sqlInsert + "id_pre_registro_linea_comercial" + ")";
            sqlInsert = sqlInsert + " VALUES (";
            sqlInsert = sqlInsert + preRegistroLineaComercial.getId();
            sqlInsert = sqlInsert + " );";
            ExcelDefault.setValueCell(sqlInsert, dataRow.createCell(contador), "S", cellStyleList);
            contador++;
        }
        return book;
    }

    protected PreRegistroLineaComercial completarDatosBean(PreRegistroLineaComercial bean) {
        BigDecimal data = new BigDecimal(0.00);
        bean = this.setCompletarDatosBean(bean);
        return bean;
    }

    protected PreRegistroLineaComercial setCompletarDatosBean(PreRegistroLineaComercial bean) {
        return bean;
    }

    /**
     * Save the passed dto as a new entity or update the corresponding entity if any.
     */
    public PreRegistroLineaComercial save(PreRegistroLineaComercial dto) {
        log.debug("Ingresando save: ", dto);
        if (dto == null) {
            return null;
        }
        dto = this.completarDatosBean(dto);
        dto = this.setBeforeSave(dto);
        this.setSave(dto);
        dto = this.preRegistroLineaComercialRepository.save(dto);
        dto = this.setAfterSave(dto);
        return dto;
    }

    protected abstract void setSave(PreRegistroLineaComercial dto);

    protected PreRegistroLineaComercial setBeforeSave(PreRegistroLineaComercial dto) {
        return dto;
    }

    protected PreRegistroLineaComercial setAfterSave(PreRegistroLineaComercial dto) {
        return dto;
    }

    /**
    * Save new entity or update the corresponding entity if any.
    */
    public PreRegistroLineaComercial create(PreRegistroLineaComercial dto) {
        log.debug("Ingresando create: ", dto);
        if (dto == null) {
            return null;
        }

        PreRegistroLineaComercial preRegistroLineaComercial;
        preRegistroLineaComercial = new PreRegistroLineaComercial();

        preRegistroLineaComercial = this.completarDatosBean(preRegistroLineaComercial);
        this.setCreate(preRegistroLineaComercial);
        return this.preRegistroLineaComercialRepository.save(preRegistroLineaComercial);
    }

    protected abstract void setCreate(PreRegistroLineaComercial dto);

    protected String validacionesPrevias(PreRegistroLineaComercial dto) {
        return "";
    }

    /**
     * Delete the passed dto as a new entity or update the corresponding entity if any.
     */
    public void delete(Integer id) {
        log.debug("Ingresando delete: ", id);
        if (id == null) {
            return;
        }
        this.setDelete(id);
        this.preRegistroLineaComercialRepository.deleteById(id);
    }

    protected abstract void setDelete(Integer id);

    public void deleteAll() {
        log.debug("Ingresando deleteAll");
        this.setDeleteAll();
        this.preRegistroLineaComercialRepository.deleteAll();
    }

    protected abstract void setDeleteAll();

    /**
     * Converts the passed preRegistroLineaComercial to a DTO.
     */
    protected PreRegistroLineaComercial toDTO(PreRegistroLineaComercial preRegistroLineaComercial) {
        return preRegistroLineaComercial;
    }

    /**
     * Converts the passed dto to a PreRegistroLineaComercial.
     * Convenient for query by example.
     */
    protected PreRegistroLineaComercial toEntity(PreRegistroLineaComercial dto) {
        return dto;
    }

}