/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTOService.java.e.vm
 */
package com.incloud.hcp.service.impl;

import com.incloud.hcp.config.excel.ExcelDefault;
import com.incloud.hcp.domain.ProveedorPreguntaInformacion;
import com.incloud.hcp.domain.ProveedorPreguntaInformacion_;
import com.incloud.hcp.dto.PreguntaInformacionInDto;
import com.incloud.hcp.dto.PreguntaInformacionOutDto;
import com.incloud.hcp.dto.ProductoDto;
import com.incloud.hcp.dto.ProductoOutDto;
import com.incloud.hcp.myibatis.mapper.ProveedorPreguntaInformacionMapper;
import com.incloud.hcp.repository.PreguntaInformacionRepository;
import com.incloud.hcp.repository.ProveedorPreguntaInformacionRepository;
import com.incloud.hcp.repository.ProveedorRepository;
import com.incloud.hcp.service.PreguntaInformacionService;
import com.incloud.hcp.service.ProveedorPreguntaInformacionService;
import com.incloud.hcp.service.ProveedorService;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.service.support.PageResponse;
import org.apache.commons.lang.StringUtils;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.DataFormat;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.streaming.SXSSFSheet;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.MessageSource;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.awt.*;
import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * A simple DTO Facility for ProveedorPreguntaInformacion.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public abstract class ProveedorPreguntaInformacionServiceImpl implements ProveedorPreguntaInformacionService {

    protected final Logger log = LoggerFactory.getLogger(ProveedorPreguntaInformacionServiceImpl.class);

    protected final String NAME_SHEET = "ProveedorPreguntaInformacion";
    protected final String CONFIG_TITLE = "com/incloud/hcp/excel/ProveedorPreguntaInformacionExcel.xml";

    @Autowired
    protected MessageSource messageSource;

    @Autowired
    protected ProveedorPreguntaInformacionRepository proveedorPreguntaInformacionRepository;

    @Autowired
    protected ProveedorService proveedorService;

    @Autowired
    protected ProveedorRepository proveedorRepository;

    @Autowired
    protected PreguntaInformacionService preguntaInformacionService;

    @Autowired
    protected PreguntaInformacionRepository preguntaInformacionRepository;

    @Transactional(readOnly = true)
    public Optional<ProveedorPreguntaInformacion> findOne(Integer id) {
        log.debug("Ingresando findOne: ", id);
        return this.proveedorPreguntaInformacionRepository.findById(id);
    }

    @Transactional(readOnly = true)
    public List<ProveedorPreguntaInformacion> findAll() {
        log.debug("Ingresando findAll");
        Sort sort = Sort.by("id");
        sort = this.setFindAll(sort);
        List<ProveedorPreguntaInformacion> lista = this.proveedorPreguntaInformacionRepository.findAll(sort);
        return lista;
    }

    protected abstract Sort setFindAll(Sort sort);

    @Transactional(readOnly = true)
    public List<ProveedorPreguntaInformacion> find(ProveedorPreguntaInformacion req) {
        log.debug("Ingresando find: ", req);
        Example<ProveedorPreguntaInformacion> example = null;
        ProveedorPreguntaInformacion proveedorPreguntaInformacion = req;
        ExampleMatcher matcher = null;
        if (proveedorPreguntaInformacion != null) {
            matcher = ExampleMatcher.matching() //
                    .withMatcher(ProveedorPreguntaInformacion_.respuesta.getName(), match -> match.ignoreCase().startsWith());
            example = Example.of(proveedorPreguntaInformacion, matcher);
        }
        Sort sort = Sort.by("id");
        sort = this.setFind(req, matcher, example, sort);
        List<ProveedorPreguntaInformacion> lista = this.proveedorPreguntaInformacionRepository.findAll(example, sort);
        return lista;
    }

    protected abstract Sort setFind(ProveedorPreguntaInformacion req, ExampleMatcher matcher, Example<ProveedorPreguntaInformacion> example, Sort sort);

    @Transactional(readOnly = true)
    public PageResponse<ProveedorPreguntaInformacion> findPaginated(PageRequestByExample<ProveedorPreguntaInformacion> req) {
        log.debug("Ingresando findPaginated: ", req);
        Example<ProveedorPreguntaInformacion> example = null;
        ProveedorPreguntaInformacion proveedorPreguntaInformacion = toEntity(req.example);
        ExampleMatcher matcher = null;
        if (proveedorPreguntaInformacion != null) {
            matcher = ExampleMatcher.matching() //
                    .withMatcher(ProveedorPreguntaInformacion_.respuesta.getName(), match -> match.ignoreCase().startsWith());
            example = Example.of(proveedorPreguntaInformacion, matcher);
        }

        Page<ProveedorPreguntaInformacion> page;
        Sort sort = Sort.by("id");
        sort = this.setFind(proveedorPreguntaInformacion, matcher, example, sort);
        req.generarLazyDefecto();
        this.setFindPaginated(req, matcher, example);
        if (example != null) {
            page = this.proveedorPreguntaInformacionRepository.findAll(example, req.toPageable(sort));
        } else {
            page = this.proveedorPreguntaInformacionRepository.findAll(req.toPageable(sort));
        }

        List<ProveedorPreguntaInformacion> content = page.getContent().stream().map(this::toDTO).collect(Collectors.toList());
        return new PageResponse<>(page.getTotalPages(), page.getTotalElements(), content);
    }

    protected abstract void setFindPaginated(PageRequestByExample<ProveedorPreguntaInformacion> req, ExampleMatcher matcher,
            Example<ProveedorPreguntaInformacion> example);

    @Transactional(readOnly = true)
    public XSSFWorkbook downloadExcelXLSX(ProveedorPreguntaInformacion req) {
        log.debug("Ingresando downloadExcelXLSX: ", req);
        List<ProveedorPreguntaInformacion> lista = this.find(req);
        Optional<List<ProveedorPreguntaInformacion>> oList = Optional.ofNullable(lista);
        if (!oList.isPresent()) {
            return null;
        }

        XSSFWorkbook book = new XSSFWorkbook();
        XSSFSheet sheet = book.createSheet();
        int numberOfSheets = book.getNumberOfSheets();
        book.setSheetName(numberOfSheets - 1, NAME_SHEET);
        ExcelDefault.createTitle(sheet, CONFIG_TITLE, book.createCellStyle(), book.createFont());
        CellStyle cellStyle = book.createCellStyle();
        DataFormat dataFormat = book.createDataFormat();

        lista.forEach(proveedorPreguntaInformacion -> {
            int lastRow = sheet.getLastRowNum();
            int i = lastRow < 0 ? 0 : lastRow;
            XSSFRow dataRow = sheet.createRow(i + 1);
            int contador = 0;
            ExcelDefault.setValueCell(proveedorPreguntaInformacion.getId(), dataRow.createCell(contador), cellStyle, dataFormat);
            contador++;
            ExcelDefault.setValueCell(proveedorPreguntaInformacion.getRespuesta(), dataRow.createCell(contador), cellStyle, dataFormat);
            contador++;
            /* Agregar aqui si desean colocar mas campos del BEAN */
            this.setDownloadExcelItem(proveedorPreguntaInformacion, dataRow);

        });
        this.setDownloadExcel(sheet);
        int totalColumn = sheet.getRow(0).getLastCellNum();
        for (int i = 0; i < totalColumn; i++) {
            sheet.autoSizeColumn(i, true);
        }
        return book;
    }

    protected void setDownloadExcelItem(ProveedorPreguntaInformacion bean, XSSFRow dataRow) {

    }

    protected void setDownloadExcel(XSSFSheet sheet) {

    }

    @Transactional(readOnly = true)
    public SXSSFWorkbook downloadExcelSXLSX(ProveedorPreguntaInformacion req) {
        log.debug("Ingresando downloadExcelSXLSX: ", req);
        List<ProveedorPreguntaInformacion> lista = this.find(req);
        Optional<List<ProveedorPreguntaInformacion>> oList = Optional.ofNullable(lista);
        if (!oList.isPresent()) {
            return null;
        }

        SXSSFWorkbook book = new SXSSFWorkbook(100);
        XSSFWorkbook xbook = book.getXSSFWorkbook();
        SXSSFSheet sheet = book.createSheet();
        sheet.trackAllColumnsForAutoSizing();
        int numberOfSheets = book.getNumberOfSheets();
        book.setSheetName(numberOfSheets - 1, NAME_SHEET);
        int nroColumnas = ExcelDefault.createTitle(xbook, sheet, CONFIG_TITLE);
        for (int i = 0; i < nroColumnas; i++) {
            sheet.autoSizeColumn(i, true);
        }
        sheet.untrackAllColumnsForAutoSizing();

        XSSFCellStyle cellStyle01 = ExcelDefault.devuelveCellStyle(xbook, new Color(0, 0, 1), new Color(226, 239, 218), false, (short) 10);
        XSSFCellStyle cellStyle02 = ExcelDefault.devuelveCellStyle(xbook, new Color(0, 0, 192), new Color(255, 255, 255), false, (short) 10);
        List<CellStyle> cellStyleList = null;
        List<CellStyle> cellStyleList01 = ExcelDefault.generarCellStyle(xbook, cellStyle01);
        List<CellStyle> cellStyleList02 = ExcelDefault.generarCellStyle(xbook, cellStyle02);
        boolean filaImpar = true;

        for (ProveedorPreguntaInformacion proveedorPreguntaInformacion : lista) {
            int lastRow = sheet.getLastRowNum();
            int i = lastRow < 0 ? 0 : lastRow;
            Row dataRow = sheet.createRow(i + 1);
            int contador = 0;
            if (filaImpar) {
                cellStyleList = cellStyleList01;
            } else {
                cellStyleList = cellStyleList02;
            }
            filaImpar = !filaImpar;

            ExcelDefault.setValueCell(proveedorPreguntaInformacion.getId(), dataRow.createCell(contador), "I", cellStyleList);
            contador++;
            ExcelDefault.setValueCell(proveedorPreguntaInformacion.getRespuesta(), dataRow.createCell(contador), "S", cellStyleList);
            contador++;
            /* Agregar aqui si desean colocar mas campos del BEAN */
            this.setDownloadExcelItem(proveedorPreguntaInformacion, dataRow);

        }
        this.setDownloadExcel(sheet);
        return book;
    }

    protected void setDownloadExcelItem(ProveedorPreguntaInformacion bean, Row dataRow) {

    }

    protected void setDownloadExcel(Sheet sheet) {

    }

    @Transactional(readOnly = true)
    public SXSSFWorkbook generateInsertExcelSXLSX(ProveedorPreguntaInformacion req) {
        log.debug("Ingresando generateInsertExcelSXLSX: ", req);
        List<ProveedorPreguntaInformacion> lista = this.find(req);
        Optional<List<ProveedorPreguntaInformacion>> oList = Optional.ofNullable(lista);
        if (!oList.isPresent()) {
            return null;
        }

        SXSSFWorkbook book = new SXSSFWorkbook(100);
        XSSFWorkbook xbook = book.getXSSFWorkbook();
        SXSSFSheet sheet = book.createSheet();
        sheet.trackAllColumnsForAutoSizing();
        int numberOfSheets = book.getNumberOfSheets();
        book.setSheetName(numberOfSheets - 1, NAME_SHEET);
        int nroColumnas = 1;
        for (int i = 0; i < nroColumnas; i++) {
            sheet.autoSizeColumn(i, true);
        }
        sheet.untrackAllColumnsForAutoSizing();
        XSSFCellStyle cellStyle01 = ExcelDefault.devuelveCellStyle(xbook, new Color(0, 0, 1), new Color(226, 239, 218), false, (short) 10);
        XSSFCellStyle cellStyle02 = ExcelDefault.devuelveCellStyle(xbook, new Color(0, 0, 192), new Color(255, 255, 255), false, (short) 10);
        List<CellStyle> cellStyleList = null;
        List<CellStyle> cellStyleList01 = ExcelDefault.generarCellStyle(xbook, cellStyle01);
        List<CellStyle> cellStyleList02 = ExcelDefault.generarCellStyle(xbook, cellStyle02);
        boolean filaImpar = true;

        for (ProveedorPreguntaInformacion proveedorPreguntaInformacion : lista) {
            int lastRow = sheet.getLastRowNum();
            int i = lastRow < 0 ? 0 : lastRow;
            Row dataRow = sheet.createRow(i + 1);
            int contador = 0;
            if (filaImpar) {
                cellStyleList = cellStyleList01;
            } else {
                cellStyleList = cellStyleList02;
            }
            filaImpar = !filaImpar;
            String sqlInsert = "INSERT INTO proveedor_pregunta_informacion(";
            sqlInsert = sqlInsert + "id_proveedor_pregunta_informacion" + ", ";
            sqlInsert = sqlInsert + "respuesta" + ")";
            sqlInsert = sqlInsert + " VALUES (";
            sqlInsert = sqlInsert + proveedorPreguntaInformacion.getId() + ", ";
            if (StringUtils.isBlank(proveedorPreguntaInformacion.getRespuesta())) {
                sqlInsert = sqlInsert + "null";
            } else {
                sqlInsert = sqlInsert + "'" + proveedorPreguntaInformacion.getRespuesta() + "'";
            }
            sqlInsert = sqlInsert + " );";
            ExcelDefault.setValueCell(sqlInsert, dataRow.createCell(contador), "S", cellStyleList);
            contador++;
        }
        return book;
    }

    protected ProveedorPreguntaInformacion completarDatosBean(ProveedorPreguntaInformacion bean) {
        BigDecimal data = new BigDecimal(0.00);
        bean = this.setCompletarDatosBean(bean);
        return bean;
    }

    protected ProveedorPreguntaInformacion setCompletarDatosBean(ProveedorPreguntaInformacion bean) {
        return bean;
    }

    /**
     * Save the passed dto as a new entity or update the corresponding entity if any.
     */
    public ProveedorPreguntaInformacion save(ProveedorPreguntaInformacion dto) {
        log.debug("Ingresando save: ", dto);
        if (dto == null) {
            return null;
        }
        dto = this.completarDatosBean(dto);
        dto = this.setBeforeSave(dto);
        this.setSave(dto);
        dto = this.proveedorPreguntaInformacionRepository.save(dto);
        dto = this.setAfterSave(dto);
        return dto;
    }

    protected abstract void setSave(ProveedorPreguntaInformacion dto);

    protected ProveedorPreguntaInformacion setBeforeSave(ProveedorPreguntaInformacion dto) {
        return dto;
    }

    protected ProveedorPreguntaInformacion setAfterSave(ProveedorPreguntaInformacion dto) {
        return dto;
    }

    /**
    * Save new entity or update the corresponding entity if any.
    */
    public ProveedorPreguntaInformacion create(ProveedorPreguntaInformacion dto) {
        log.debug("Ingresando create: ", dto);
        if (dto == null) {
            return null;
        }

        ProveedorPreguntaInformacion proveedorPreguntaInformacion;
        proveedorPreguntaInformacion = new ProveedorPreguntaInformacion();

        proveedorPreguntaInformacion.setRespuesta(dto.getRespuesta());
        proveedorPreguntaInformacion = this.completarDatosBean(proveedorPreguntaInformacion);
        this.setCreate(proveedorPreguntaInformacion);
        return this.proveedorPreguntaInformacionRepository.save(proveedorPreguntaInformacion);
    }

    protected abstract void setCreate(ProveedorPreguntaInformacion dto);

    protected String validacionesPrevias(ProveedorPreguntaInformacion dto) {
        return "";
    }

    /**
     * Delete the passed dto as a new entity or update the corresponding entity if any.
     */
    public void delete(Integer id) {
        log.debug("Ingresando delete: ", id);
        if (id == null) {
            return;
        }
        this.setDelete(id);
        this.proveedorPreguntaInformacionRepository.deleteById(id);
    }

    protected abstract void setDelete(Integer id);

    public void deleteAll() {
        log.debug("Ingresando deleteAll");
        this.setDeleteAll();
        this.proveedorPreguntaInformacionRepository.deleteAll();
    }

    protected abstract void setDeleteAll();

    /**
     * Converts the passed proveedorPreguntaInformacion to a DTO.
     */
    protected ProveedorPreguntaInformacion toDTO(ProveedorPreguntaInformacion proveedorPreguntaInformacion) {
        return proveedorPreguntaInformacion;
    }

    /**
     * Converts the passed dto to a ProveedorPreguntaInformacion.
     * Convenient for query by example.
     */
    protected ProveedorPreguntaInformacion toEntity(ProveedorPreguntaInformacion dto) {
        return dto;
    }




}