/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTOService.java.e.vm
 */
package com.incloud.hcp.service.impl;

import com.incloud.hcp.config.excel.ExcelDefault;
import com.incloud.hcp.domain.ProveedorPermiso;
import com.incloud.hcp.domain.ProveedorPermiso_;
import com.incloud.hcp.repository.ProveedorPermisoRepository;
import com.incloud.hcp.repository.ProveedorRepository;
import com.incloud.hcp.service.ProveedorPermisoService;
import com.incloud.hcp.service.ProveedorService;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.service.support.PageResponse;
import org.apache.commons.lang.StringUtils;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.DataFormat;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.xssf.streaming.SXSSFSheet;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.MessageSource;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.awt.*;
import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * A simple DTO Facility for ProveedorPermiso.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public abstract class ProveedorPermisoServiceImpl implements ProveedorPermisoService {

    protected final Logger log = LoggerFactory.getLogger(ProveedorPermisoServiceImpl.class);

    protected final String NAME_SHEET = "ProveedorPermiso";
    protected final String CONFIG_TITLE = "com/incloud/hcp/excel/ProveedorPermisoExcel.xml";

    @Autowired
    protected MessageSource messageSource;

    @Autowired
    protected ProveedorPermisoRepository proveedorPermisoRepository;

    @Autowired
    protected ProveedorService proveedorService;

    @Autowired
    protected ProveedorRepository proveedorRepository;

    @Transactional(readOnly = true)
    public Optional<ProveedorPermiso> findOne(Integer id) {
        log.debug("Ingresando findOne: ", id);
        return this.proveedorPermisoRepository.findById(id);
    }

    @Transactional(readOnly = true)
    public List<ProveedorPermiso> findAll() {
        log.debug("Ingresando findAll");
        Sort sort = Sort.by("id");
        sort = this.setFindAll(sort);
        List<ProveedorPermiso> lista = this.proveedorPermisoRepository.findAll(sort);
        return lista;
    }

    protected abstract Sort setFindAll(Sort sort);

    @Transactional(readOnly = true)
    public List<ProveedorPermiso> find(ProveedorPermiso req) {
        log.debug("Ingresando find: ", req);
        Example<ProveedorPermiso> example = null;
        ProveedorPermiso proveedorPermiso = req;
        ExampleMatcher matcher = null;
        if (proveedorPermiso != null) {
            matcher = ExampleMatcher.matching() //
                    .withMatcher(ProveedorPermiso_.codigoTipoPermiso.getName(), match -> match.ignoreCase().startsWith())
                    .withMatcher(ProveedorPermiso_.entidadEmisora.getName(), match -> match.ignoreCase().startsWith())
                    .withMatcher(ProveedorPermiso_.vigencia.getName(), match -> match.ignoreCase().startsWith());
            example = Example.of(proveedorPermiso, matcher);
        }
        Sort sort = Sort.by("id");
        sort = this.setFind(req, matcher, example, sort);
        List<ProveedorPermiso> lista = this.proveedorPermisoRepository.findAll(example, sort);
        return lista;
    }

    protected abstract Sort setFind(ProveedorPermiso req, ExampleMatcher matcher, Example<ProveedorPermiso> example, Sort sort);

    @Transactional(readOnly = true)
    public PageResponse<ProveedorPermiso> findPaginated(PageRequestByExample<ProveedorPermiso> req) {
        log.debug("Ingresando findPaginated: ", req);
        Example<ProveedorPermiso> example = null;
        ProveedorPermiso proveedorPermiso = toEntity(req.example);
        ExampleMatcher matcher = null;
        if (proveedorPermiso != null) {
            matcher = ExampleMatcher.matching() //
                    .withMatcher(ProveedorPermiso_.codigoTipoPermiso.getName(), match -> match.ignoreCase().startsWith())
                    .withMatcher(ProveedorPermiso_.entidadEmisora.getName(), match -> match.ignoreCase().startsWith())
                    .withMatcher(ProveedorPermiso_.vigencia.getName(), match -> match.ignoreCase().startsWith());
            example = Example.of(proveedorPermiso, matcher);
        }

        Page<ProveedorPermiso> page;
        Sort sort = Sort.by("id");
        sort = this.setFind(proveedorPermiso, matcher, example, sort);
        req.generarLazyDefecto();
        this.setFindPaginated(req, matcher, example);
        if (example != null) {
            page = this.proveedorPermisoRepository.findAll(example, req.toPageable(sort));
        } else {
            page = this.proveedorPermisoRepository.findAll(req.toPageable(sort));
        }

        List<ProveedorPermiso> content = page.getContent().stream().map(this::toDTO).collect(Collectors.toList());
        return new PageResponse<>(page.getTotalPages(), page.getTotalElements(), content);
    }

    protected abstract void setFindPaginated(PageRequestByExample<ProveedorPermiso> req, ExampleMatcher matcher, Example<ProveedorPermiso> example);

    @Transactional(readOnly = true)
    public XSSFWorkbook downloadExcelXLSX(ProveedorPermiso req) {
        log.debug("Ingresando downloadExcelXLSX: ", req);
        List<ProveedorPermiso> lista = this.find(req);
        Optional<List<ProveedorPermiso>> oList = Optional.ofNullable(lista);
        if (!oList.isPresent()) {
            return null;
        }

        XSSFWorkbook book = new XSSFWorkbook();
        XSSFSheet sheet = book.createSheet();
        int numberOfSheets = book.getNumberOfSheets();
        book.setSheetName(numberOfSheets - 1, NAME_SHEET);
        ExcelDefault.createTitle(sheet, CONFIG_TITLE, book.createCellStyle(), book.createFont());
        CellStyle cellStyle = book.createCellStyle();
        DataFormat dataFormat = book.createDataFormat();

        lista.forEach(proveedorPermiso -> {
            int lastRow = sheet.getLastRowNum();
            int i = lastRow < 0 ? 0 : lastRow;
            XSSFRow dataRow = sheet.createRow(i + 1);
            int contador = 0;
            ExcelDefault.setValueCell(proveedorPermiso.getId(), dataRow.createCell(contador), cellStyle, dataFormat);
            contador++;
            ExcelDefault.setValueCell(proveedorPermiso.getCodigoTipoPermiso(), dataRow.createCell(contador), cellStyle, dataFormat);
            contador++;
            ExcelDefault.setValueCell(proveedorPermiso.getEntidadEmisora(), dataRow.createCell(contador), cellStyle, dataFormat);
            contador++;
            ExcelDefault.setValueCell(proveedorPermiso.getVigencia(), dataRow.createCell(contador), cellStyle, dataFormat);
            contador++;
            /* Agregar aqui si desean colocar mas campos del BEAN */
            this.setDownloadExcelItem(proveedorPermiso, dataRow);

        });
        this.setDownloadExcel(sheet);
        int totalColumn = sheet.getRow(0).getLastCellNum();
        for (int i = 0; i < totalColumn; i++) {
            sheet.autoSizeColumn(i, true);
        }
        return book;
    }

    protected void setDownloadExcelItem(ProveedorPermiso bean, XSSFRow dataRow) {

    }

    protected void setDownloadExcel(XSSFSheet sheet) {

    }

    @Transactional(readOnly = true)
    public SXSSFWorkbook downloadExcelSXLSX(ProveedorPermiso req) {
        log.debug("Ingresando downloadExcelSXLSX: ", req);
        List<ProveedorPermiso> lista = this.find(req);
        Optional<List<ProveedorPermiso>> oList = Optional.ofNullable(lista);
        if (!oList.isPresent()) {
            return null;
        }

        SXSSFWorkbook book = new SXSSFWorkbook(100);
        XSSFWorkbook xbook = book.getXSSFWorkbook();
        SXSSFSheet sheet = book.createSheet();
        sheet.trackAllColumnsForAutoSizing();
        int numberOfSheets = book.getNumberOfSheets();
        book.setSheetName(numberOfSheets - 1, NAME_SHEET);
        int nroColumnas = ExcelDefault.createTitle(xbook, sheet, CONFIG_TITLE);
        for (int i = 0; i < nroColumnas; i++) {
            sheet.autoSizeColumn(i, true);
        }
        sheet.untrackAllColumnsForAutoSizing();

        XSSFCellStyle cellStyle01 = ExcelDefault.devuelveCellStyle(xbook, new Color(0, 0, 1), new Color(226, 239, 218), false, (short) 10);
        XSSFCellStyle cellStyle02 = ExcelDefault.devuelveCellStyle(xbook, new Color(0, 0, 192), new Color(255, 255, 255), false, (short) 10);
        List<CellStyle> cellStyleList = null;
        List<CellStyle> cellStyleList01 = ExcelDefault.generarCellStyle(xbook, cellStyle01);
        List<CellStyle> cellStyleList02 = ExcelDefault.generarCellStyle(xbook, cellStyle02);
        boolean filaImpar = true;

        for (ProveedorPermiso proveedorPermiso : lista) {
            int lastRow = sheet.getLastRowNum();
            int i = lastRow < 0 ? 0 : lastRow;
            Row dataRow = sheet.createRow(i + 1);
            int contador = 0;
            if (filaImpar) {
                cellStyleList = cellStyleList01;
            } else {
                cellStyleList = cellStyleList02;
            }
            filaImpar = !filaImpar;

            ExcelDefault.setValueCell(proveedorPermiso.getId(), dataRow.createCell(contador), "I", cellStyleList);
            contador++;
            ExcelDefault.setValueCell(proveedorPermiso.getCodigoTipoPermiso(), dataRow.createCell(contador), "S", cellStyleList);
            contador++;
            ExcelDefault.setValueCell(proveedorPermiso.getEntidadEmisora(), dataRow.createCell(contador), "S", cellStyleList);
            contador++;
            ExcelDefault.setValueCell(proveedorPermiso.getVigencia(), dataRow.createCell(contador), "S", cellStyleList);
            contador++;
            /* Agregar aqui si desean colocar mas campos del BEAN */
            this.setDownloadExcelItem(proveedorPermiso, dataRow);

        }
        this.setDownloadExcel(sheet);
        return book;
    }

    protected void setDownloadExcelItem(ProveedorPermiso bean, Row dataRow) {

    }

    protected void setDownloadExcel(Sheet sheet) {

    }

    @Transactional(readOnly = true)
    public SXSSFWorkbook generateInsertExcelSXLSX(ProveedorPermiso req) {
        log.debug("Ingresando generateInsertExcelSXLSX: ", req);
        List<ProveedorPermiso> lista = this.find(req);
        Optional<List<ProveedorPermiso>> oList = Optional.ofNullable(lista);
        if (!oList.isPresent()) {
            return null;
        }

        SXSSFWorkbook book = new SXSSFWorkbook(100);
        XSSFWorkbook xbook = book.getXSSFWorkbook();
        SXSSFSheet sheet = book.createSheet();
        sheet.trackAllColumnsForAutoSizing();
        int numberOfSheets = book.getNumberOfSheets();
        book.setSheetName(numberOfSheets - 1, NAME_SHEET);
        int nroColumnas = 1;
        for (int i = 0; i < nroColumnas; i++) {
            sheet.autoSizeColumn(i, true);
        }
        sheet.untrackAllColumnsForAutoSizing();
        XSSFCellStyle cellStyle01 = ExcelDefault.devuelveCellStyle(xbook, new Color(0, 0, 1), new Color(226, 239, 218), false, (short) 10);
        XSSFCellStyle cellStyle02 = ExcelDefault.devuelveCellStyle(xbook, new Color(0, 0, 192), new Color(255, 255, 255), false, (short) 10);
        List<CellStyle> cellStyleList = null;
        List<CellStyle> cellStyleList01 = ExcelDefault.generarCellStyle(xbook, cellStyle01);
        List<CellStyle> cellStyleList02 = ExcelDefault.generarCellStyle(xbook, cellStyle02);
        boolean filaImpar = true;

        for (ProveedorPermiso proveedorPermiso : lista) {
            int lastRow = sheet.getLastRowNum();
            int i = lastRow < 0 ? 0 : lastRow;
            Row dataRow = sheet.createRow(i + 1);
            int contador = 0;
            if (filaImpar) {
                cellStyleList = cellStyleList01;
            } else {
                cellStyleList = cellStyleList02;
            }
            filaImpar = !filaImpar;
            String sqlInsert = "INSERT INTO proveedor_permiso(";
            sqlInsert = sqlInsert + "id_proveedor_permiso" + ", ";
            sqlInsert = sqlInsert + "codigo_tipo_permiso" + ", ";
            sqlInsert = sqlInsert + "entidad_emisora" + ", ";
            sqlInsert = sqlInsert + "vigencia" + ")";
            sqlInsert = sqlInsert + " VALUES (";
            sqlInsert = sqlInsert + proveedorPermiso.getId() + ", ";
            if (StringUtils.isBlank(proveedorPermiso.getCodigoTipoPermiso())) {
                sqlInsert = sqlInsert + "null" + ", ";
            } else {
                sqlInsert = sqlInsert + "'" + proveedorPermiso.getCodigoTipoPermiso() + "'" + ", ";
            }
            if (StringUtils.isBlank(proveedorPermiso.getEntidadEmisora())) {
                sqlInsert = sqlInsert + "null" + ", ";
            } else {
                sqlInsert = sqlInsert + "'" + proveedorPermiso.getEntidadEmisora() + "'" + ", ";
            }
            if (StringUtils.isBlank(proveedorPermiso.getVigencia())) {
                sqlInsert = sqlInsert + "null";
            } else {
                sqlInsert = sqlInsert + "'" + proveedorPermiso.getVigencia() + "'";
            }
            sqlInsert = sqlInsert + " );";
            ExcelDefault.setValueCell(sqlInsert, dataRow.createCell(contador), "S", cellStyleList);
            contador++;
        }
        return book;
    }

    protected ProveedorPermiso completarDatosBean(ProveedorPermiso bean) {
        BigDecimal data = new BigDecimal(0.00);
        bean = this.setCompletarDatosBean(bean);
        return bean;
    }

    protected ProveedorPermiso setCompletarDatosBean(ProveedorPermiso bean) {
        return bean;
    }

    /**
     * Save the passed dto as a new entity or update the corresponding entity if any.
     */
    public ProveedorPermiso save(ProveedorPermiso dto) {
        log.debug("Ingresando save: ", dto);
        if (dto == null) {
            return null;
        }
        dto = this.completarDatosBean(dto);
        dto = this.setBeforeSave(dto);
        this.setSave(dto);
        dto = this.proveedorPermisoRepository.save(dto);
        dto = this.setAfterSave(dto);
        return dto;
    }

    protected abstract void setSave(ProveedorPermiso dto);

    protected ProveedorPermiso setBeforeSave(ProveedorPermiso dto) {
        return dto;
    }

    protected ProveedorPermiso setAfterSave(ProveedorPermiso dto) {
        return dto;
    }

    /**
    * Save new entity or update the corresponding entity if any.
    */
    public ProveedorPermiso create(ProveedorPermiso dto) {
        log.debug("Ingresando create: ", dto);
        if (dto == null) {
            return null;
        }

        ProveedorPermiso proveedorPermiso;
        proveedorPermiso = new ProveedorPermiso();

        proveedorPermiso.setCodigoTipoPermiso(dto.getCodigoTipoPermiso());
        proveedorPermiso.setEntidadEmisora(dto.getEntidadEmisora());
        proveedorPermiso.setVigencia(dto.getVigencia());
        proveedorPermiso = this.completarDatosBean(proveedorPermiso);
        this.setCreate(proveedorPermiso);
        return this.proveedorPermisoRepository.save(proveedorPermiso);
    }

    protected abstract void setCreate(ProveedorPermiso dto);

    protected String validacionesPrevias(ProveedorPermiso dto) {
        return "";
    }

    /**
     * Delete the passed dto as a new entity or update the corresponding entity if any.
     */
    public void delete(Integer id) {
        log.debug("Ingresando delete: ", id);
        if (id == null) {
            return;
        }
        this.setDelete(id);
        this.proveedorPermisoRepository.deleteById(id);
    }

    protected abstract void setDelete(Integer id);

    public void deleteAll() {
        log.debug("Ingresando deleteAll");
        this.setDeleteAll();
        this.proveedorPermisoRepository.deleteAll();
    }

    protected abstract void setDeleteAll();

    /**
     * Converts the passed proveedorPermiso to a DTO.
     */
    protected ProveedorPermiso toDTO(ProveedorPermiso proveedorPermiso) {
        return proveedorPermiso;
    }

    /**
     * Converts the passed dto to a ProveedorPermiso.
     * Convenient for query by example.
     */
    protected ProveedorPermiso toEntity(ProveedorPermiso dto) {
        return dto;
    }

}