
package com.incloud.hcp.wsdl.materiales;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "SI_P027_MaestroMateriales_Req_Sync_Out", targetNamespace = "urn:sanmartinperu.pe:portal027:MaestroMateriales")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface SIP027MaestroMaterialesReqSyncOut {


    /**
     *
     * @param mtP027MaestroMaterialesReqOut
     * @return
     *     returns com.incloud.hcp.wsdl.materiales.DTP027MaestroMaterialesRes
     */
    @WebMethod(operationName = "SI_P027_MaestroMateriales_Req_Sync_Out", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_P027_MaestroMateriales_Res_In", targetNamespace = "urn:sanmartinperu.pe:portal027:MaestroMateriales", partName = "MT_P027_MaestroMateriales_Res_In")
    public DTP027MaestroMaterialesRes siP027MaestroMaterialesReqSyncOut(
            @WebParam(name = "MT_P027_MaestroMateriales_Req_Out", targetNamespace = "urn:sanmartinperu.pe:portal027:MaestroMateriales", partName = "MT_P027_MaestroMateriales_Req_Out")
                    DTP027MaestroMaterialesReq mtP027MaestroMaterialesReqOut);

}