/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntitydeltaDTO.java.e.vm
 */
package com.incloud.hcp.service.delta;

import com.incloud.hcp.domain.LicitacionProveedorPregunta;
import com.incloud.hcp.service.LicitacionProveedorPreguntaService;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;

import java.util.List;

/**
 * Simple Interface for LicitacionProveedorPregunta.
 */
public interface LicitacionProveedorPreguntaDeltaService extends LicitacionProveedorPreguntaService {

    List<LicitacionProveedorPregunta> grabar(List<LicitacionProveedorPregunta> licitacionProveedorPreguntaList) throws Exception;

    String enviarCorreoPreguntaLicitacion(List<LicitacionProveedorPregunta> licitacionProveedorPreguntaList);

    SXSSFWorkbook downloadExcelSXLSXLicitacion(LicitacionProveedorPregunta req);

}
