/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntitydeltaDTO.java.e.vm
 */
package com.incloud.hcp.service.delta;

import com.incloud.hcp.dto.ClienteInDto;
import com.incloud.hcp.dto.ClienteOutDto;
import com.incloud.hcp.dto.FuncionarioInDto;
import com.incloud.hcp.dto.FuncionarioOutDto;
import com.incloud.hcp.service.ProveedorClienteService;

/**
 * Simple Interface for ProveedorCliente.
 */
public interface ProveedorClienteDeltaService extends ProveedorClienteService {

    public ClienteOutDto crearCliente(ClienteInDto bean);
}
