/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.incloud.hcp.service;

import com.incloud.hcp.domain.CcomparativoProveedor;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.service.support.PageResponse;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.util.List;
import java.util.Optional;

/**
 * Simple Interface for CcomparativoProveedor.
 */
public interface CcomparativoProveedorService {

    Optional<CcomparativoProveedor> findOne(Integer id);

    List<CcomparativoProveedor> findAll();

    List<CcomparativoProveedor> find(CcomparativoProveedor req);

    PageResponse<CcomparativoProveedor> findPaginated(PageRequestByExample<CcomparativoProveedor> req);

    XSSFWorkbook downloadExcelXLSX(CcomparativoProveedor req);

    SXSSFWorkbook downloadExcelSXLSX(CcomparativoProveedor req);

    SXSSFWorkbook generateInsertExcelSXLSX(CcomparativoProveedor req);

    CcomparativoProveedor save(CcomparativoProveedor dto);

    CcomparativoProveedor create(CcomparativoProveedor dto);

    void delete(Integer id);

    void deleteAll();

}
