/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.incloud.hcp.service;

import com.incloud.hcp.domain.CotizacionRechazada;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.service.support.PageResponse;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.util.List;
import java.util.Optional;

/**
 * Simple Interface for CotizacionRechazada.
 */
public interface CotizacionRechazadaService {

    Optional<CotizacionRechazada> findOne(Integer id);

    List<CotizacionRechazada> findAll();

    List<CotizacionRechazada> find(CotizacionRechazada req);

    PageResponse<CotizacionRechazada> findPaginated(PageRequestByExample<CotizacionRechazada> req);

    XSSFWorkbook downloadExcelXLSX(CotizacionRechazada req);

    SXSSFWorkbook downloadExcelSXLSX(CotizacionRechazada req);

    SXSSFWorkbook generateInsertExcelSXLSX(CotizacionRechazada req);

    CotizacionRechazada save(CotizacionRechazada dto);

    CotizacionRechazada create(CotizacionRechazada dto);

    void delete(Integer id);

    void deleteAll();

}
