/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.incloud.hcp.service;

import com.incloud.hcp.domain.LicitacionProveedorPregunta;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.service.support.PageResponse;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Simple Interface for LicitacionProveedorPregunta.
 */
public interface LicitacionProveedorPreguntaService {

    Optional<LicitacionProveedorPregunta> findOne(Integer id);

    List<LicitacionProveedorPregunta> findAll();

    List<LicitacionProveedorPregunta> find(LicitacionProveedorPregunta req);

    PageResponse<LicitacionProveedorPregunta> findPaginated(PageRequestByExample<LicitacionProveedorPregunta> req);

    XSSFWorkbook downloadExcelXLSX(LicitacionProveedorPregunta req);

    SXSSFWorkbook downloadExcelSXLSX(LicitacionProveedorPregunta req);

    SXSSFWorkbook generateInsertExcelSXLSX(LicitacionProveedorPregunta req);

    LicitacionProveedorPregunta save(LicitacionProveedorPregunta dto);

    LicitacionProveedorPregunta create(LicitacionProveedorPregunta dto);

    void delete(Integer id);

    Map<String, Object> downloadExcel(Integer idLicitacion);

    Map<String, Object> downloadExcelPrueba(Integer idLicitacion);

    void deleteAll();

}
