/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.incloud.hcp.service;

import com.incloud.hcp.domain.PreguntaInformacion;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.service.support.PageResponse;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.util.List;
import java.util.Optional;

/**
 * Simple Interface for PreguntaInformacion.
 */
public interface PreguntaInformacionService {

    Optional<PreguntaInformacion> findOne(Integer id);

    List<PreguntaInformacion> findAll();

    List<PreguntaInformacion> find(PreguntaInformacion req);

    PageResponse<PreguntaInformacion> findPaginated(PageRequestByExample<PreguntaInformacion> req);

    XSSFWorkbook downloadExcelXLSX(PreguntaInformacion req);

    SXSSFWorkbook downloadExcelSXLSX(PreguntaInformacion req);

    SXSSFWorkbook generateInsertExcelSXLSX(PreguntaInformacion req);

    PreguntaInformacion save(PreguntaInformacion dto);

    PreguntaInformacion create(PreguntaInformacion dto);

    void delete(Integer id);

    void deleteAll();

}
