/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.incloud.hcp.service;

import com.incloud.hcp.domain.ProveedorCliente;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.service.support.PageResponse;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.util.List;
import java.util.Optional;

/**
 * Simple Interface for ProveedorCliente.
 */
public interface ProveedorClienteService {

    Optional<ProveedorCliente> findOne(Integer id);

    List<ProveedorCliente> findAll();

    List<ProveedorCliente> find(ProveedorCliente req);

    PageResponse<ProveedorCliente> findPaginated(PageRequestByExample<ProveedorCliente> req);

    XSSFWorkbook downloadExcelXLSX(ProveedorCliente req);

    SXSSFWorkbook downloadExcelSXLSX(ProveedorCliente req);

    SXSSFWorkbook generateInsertExcelSXLSX(ProveedorCliente req);

    ProveedorCliente save(ProveedorCliente dto);

    ProveedorCliente create(ProveedorCliente dto);

    void delete(Integer id);

    void deleteAll();

}
