/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.incloud.hcp.service;

import com.incloud.hcp.domain.ProveedorPermiso;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.service.support.PageResponse;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.util.List;
import java.util.Optional;

/**
 * Simple Interface for ProveedorPermiso.
 */
public interface ProveedorPermisoService {

    Optional<ProveedorPermiso> findOne(Integer id);

    List<ProveedorPermiso> findAll();

    List<ProveedorPermiso> find(ProveedorPermiso req);

    PageResponse<ProveedorPermiso> findPaginated(PageRequestByExample<ProveedorPermiso> req);

    XSSFWorkbook downloadExcelXLSX(ProveedorPermiso req);

    SXSSFWorkbook downloadExcelSXLSX(ProveedorPermiso req);

    SXSSFWorkbook generateInsertExcelSXLSX(ProveedorPermiso req);

    ProveedorPermiso save(ProveedorPermiso dto);

    ProveedorPermiso create(ProveedorPermiso dto);

    void delete(Integer id);

    void deleteAll();

}
