/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.incloud.hcp.service;

import com.incloud.hcp.domain.ProveedorFuncionario;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.service.support.PageResponse;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.util.List;
import java.util.Optional;

/**
 * Simple Interface for ProveedorFuncionario.
 */
public interface ProveedorFuncionarioService {

    Optional<ProveedorFuncionario> findOne(Integer id);

    List<ProveedorFuncionario> findAll();

    List<ProveedorFuncionario> find(ProveedorFuncionario req);

    PageResponse<ProveedorFuncionario> findPaginated(PageRequestByExample<ProveedorFuncionario> req);

    XSSFWorkbook downloadExcelXLSX(ProveedorFuncionario req);

    SXSSFWorkbook downloadExcelSXLSX(ProveedorFuncionario req);

    SXSSFWorkbook generateInsertExcelSXLSX(ProveedorFuncionario req);

    ProveedorFuncionario save(ProveedorFuncionario dto);

    ProveedorFuncionario create(ProveedorFuncionario dto);

    void delete(Integer id);

    void deleteAll();

}
