/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.incloud.hcp.service;

import com.incloud.hcp.domain.TasaCambio;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.service.support.PageResponse;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.util.List;
import java.util.Optional;

/**
 * Simple Interface for TasaCambio.
 */
public interface TasaCambioService {

    Optional<TasaCambio> findOne(Integer id);

    List<TasaCambio> findAll();

    List<TasaCambio> find(TasaCambio req);

    PageResponse<TasaCambio> findPaginated(PageRequestByExample<TasaCambio> req);

    XSSFWorkbook downloadExcelXLSX(TasaCambio req);

    SXSSFWorkbook downloadExcelSXLSX(TasaCambio req);

    SXSSFWorkbook generateInsertExcelSXLSX(TasaCambio req);

    TasaCambio save(TasaCambio dto);

    TasaCambio create(TasaCambio dto);

    void delete(Integer id);

    void deleteAll();

}
