/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.incloud.hcp.service;

import com.incloud.hcp.domain.TempBienServicio;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.service.support.PageResponse;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.util.List;
import java.util.Optional;

/**
 * Simple Interface for TempBienServicio.
 */
public interface TempBienServicioService {

    Optional<TempBienServicio> findOne(Integer id);

    List<TempBienServicio> findAll();

    List<TempBienServicio> find(TempBienServicio req);

    PageResponse<TempBienServicio> findPaginated(PageRequestByExample<TempBienServicio> req);

    XSSFWorkbook downloadExcelXLSX(TempBienServicio req);

    SXSSFWorkbook downloadExcelSXLSX(TempBienServicio req);

    SXSSFWorkbook generateInsertExcelSXLSX(TempBienServicio req);

    TempBienServicio save(TempBienServicio dto);

    TempBienServicio create(TempBienServicio dto);

    void delete(Integer id);

    void deleteAll();

}
