/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.config.BindingErrorsResponse;
import com.incloud.hcp.config.excel.ExcelType;
import com.incloud.hcp.domain.LicitacionAdjuntoRespuesta;
import com.incloud.hcp.domain.LogTransaccion;
import com.incloud.hcp.dto.LicitacionAdjuntoBase64Dto;
import com.incloud.hcp.repository.LicitacionAdjuntoRespuestaRepository;
import com.incloud.hcp.repository.LogTransaccionRepository;
import com.incloud.hcp.rest._framework.AppRest;
import com.incloud.hcp.service.delta.LicitacionAdjuntoRespuestaDeltaService;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.service.support.PageResponse;
import com.incloud.hcp.util.Utils;
import io.swagger.annotations.ApiOperation;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;
import java.io.ByteArrayOutputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.OutputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Optional;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;

public abstract class LicitacionAdjuntoRespuestaRest extends AppRest {
    private final Logger log = LoggerFactory.getLogger(LicitacionAdjuntoRespuestaRest.class);

    @Autowired
    protected LicitacionAdjuntoRespuestaRepository licitacionAdjuntoRespuestaRepository;

    @Autowired
    protected LicitacionAdjuntoRespuestaDeltaService licitacionAdjuntoRespuestaDeltaService;

    @Autowired
    private LogTransaccionRepository logTransaccionRepository;

    /**
    * Find by id LicitacionAdjuntoRespuesta.
    */
    @ApiOperation(value = "Busca registro de tipo LicitacionAdjuntoRespuesta en base al id enviado", produces = "application/json")
    @GetMapping(value = "/findById/{id}", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<LicitacionAdjuntoRespuesta> findById(@PathVariable Integer id) throws URISyntaxException {
        log.debug("Find by id LicitacionAdjuntoRespuesta : {}", id);
        try {
            return Optional.ofNullable(this.licitacionAdjuntoRespuestaDeltaService.findOne(id).get())
                    .map(licitacionAdjuntoRespuesta -> new ResponseEntity<>(licitacionAdjuntoRespuesta, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
        } catch (Exception e) {
            String error = Utils.obtieneMensajeErrorException(e);
            throw new RuntimeException(error);
        }
    }

    /**
    * Find All sin paginacion LicitacionAdjuntoRespuesta.
    */
    @ApiOperation(value = "Devuelve lista de registros de tipo LicitacionAdjuntoRespuesta", produces = "application/json")
    @GetMapping(value = "/findAll", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<LicitacionAdjuntoRespuesta>> findAll() throws URISyntaxException {
        log.debug("Ingresando findAll");
        try {
            return Optional.of(this.licitacionAdjuntoRespuestaDeltaService.findAll()).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            String error = Utils.obtieneMensajeErrorException(e);
            throw new RuntimeException(error);
        }
    }

    /**
    * Devuelve lista sin paginacion en base a los parametros ingresados en LicitacionAdjuntoRespuesta.
    */
    @ApiOperation(value = "Devuelve lista de registros de tipo LicitacionAdjuntoRespuesta en base a los parámetros ingresados", produces = "application/json")
    @PostMapping(value = "/find", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<LicitacionAdjuntoRespuesta>> find(@RequestBody LicitacionAdjuntoRespuesta bean, BindingResult bindingResult)
            throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            throw new RuntimeException(errors.toJSON());
        }
        log.debug("Ingresando find by LicitacionAdjuntoRespuesta : {}", bean);
        try {
            return Optional.of(this.licitacionAdjuntoRespuestaDeltaService.find(bean)).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            String error = Utils.obtieneMensajeErrorException(e);
            throw new RuntimeException(error);
        }
    }

    /**
     * Find a Page of LicitacionAdjuntoRespuesta using query by example.
     */
    @ApiOperation(value = "Devuelve lista de registros paginados de tipo LicitacionAdjuntoRespuesta", produces = "application/json")
    @PostMapping(value = "/findPaginated", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<LicitacionAdjuntoRespuesta>> findPaginated(@RequestBody PageRequestByExample<LicitacionAdjuntoRespuesta> prbe,
            BindingResult bindingResult) throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            throw new RuntimeException(errors.toJSON());
        }
        log.debug("Ingresando findPaginated by PageRequestByExample : {}", prbe);
        try {
            PageResponse<LicitacionAdjuntoRespuesta> pageResponse = this.licitacionAdjuntoRespuestaDeltaService.findPaginated(prbe);
            return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
        } catch (Exception e) {
            String error = Utils.obtieneMensajeErrorException(e);
            throw new RuntimeException(error);
        }
    }

    @ApiOperation(value = "Genera Excel XLSX de registros de tipo LicitacionAdjuntoRespuesta", produces = "application/vnd.ms-excel")
    @GetMapping(value = "/downloadCompleteExcelXLSX", produces = { MediaType.APPLICATION_OCTET_STREAM_VALUE })
    public ResponseEntity<?> downloadCompleteExcelXLSX(HttpServletResponse response) {
        LicitacionAdjuntoRespuesta bean = new LicitacionAdjuntoRespuesta();
        log.debug("Ingresando downloadCompleteExcelXLSX by LicitacionAdjuntoRespuesta : {}", bean);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd_hh_mm_ss");
        String excelFileName = "LicitacionAdjuntoRespuesta_" + formatter.format(LocalDateTime.now()) + ".xlsx";
        SXSSFWorkbook book = this.licitacionAdjuntoRespuestaDeltaService.downloadExcelSXLSX(bean);

        try {
            ByteArrayOutputStream outByteStream = new ByteArrayOutputStream();
            book.write(outByteStream);
            byte[] outArray = outByteStream.toByteArray();
            //response.setContentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
            response.setContentType(ExcelType.XLSX.getExtension());
            response.setContentLength(outArray.length);
            response.setHeader("Expires:", "0"); // eliminates browser caching
            response.setHeader("Content-Disposition", "attachment; filename=" + excelFileName);
            OutputStream outStream = response.getOutputStream();
            outStream.write(outArray);
            outStream.flush();

            book.dispose();
            book.close();
        } catch (FileNotFoundException e) {
            String error = Utils.obtieneMensajeErrorException(e);
            e.printStackTrace();
            throw new RuntimeException(error);
        } catch (IOException e) {
            String error = Utils.obtieneMensajeErrorException(e);
            e.printStackTrace();
            throw new RuntimeException(error);
        }
        return new ResponseEntity<>(HttpStatus.OK);
    }

    @ApiOperation(value = "Genera insert Excel XLSX de registros de tipo LicitacionAdjuntoRespuesta", produces = "application/vnd.ms-excel")
    @GetMapping(value = "/generateInsertExcelSXLSX", produces = { MediaType.APPLICATION_OCTET_STREAM_VALUE })
    public ResponseEntity<?> generateInsertExcelSXLSX(HttpServletResponse response) {
        LicitacionAdjuntoRespuesta bean = new LicitacionAdjuntoRespuesta();
        log.debug("Ingresando generateInsertExcelSXLSX by LicitacionAdjuntoRespuesta : {}", bean);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd_hh_mm_ss");
        String excelFileName = "INSERT_LicitacionAdjuntoRespuesta_" + formatter.format(LocalDateTime.now()) + ".xlsx";
        SXSSFWorkbook book = this.licitacionAdjuntoRespuestaDeltaService.generateInsertExcelSXLSX(bean);

        try {
            ByteArrayOutputStream outByteStream = new ByteArrayOutputStream();
            book.write(outByteStream);
            byte[] outArray = outByteStream.toByteArray();
            //response.setContentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
            response.setContentType(ExcelType.XLSX.getExtension());
            response.setContentLength(outArray.length);
            response.setHeader("Expires:", "0"); // eliminates browser caching
            response.setHeader("Content-Disposition", "attachment; filename=" + excelFileName);
            OutputStream outStream = response.getOutputStream();
            outStream.write(outArray);
            outStream.flush();

            book.dispose();
            book.close();
        } catch (FileNotFoundException e) {
            String error = Utils.obtieneMensajeErrorException(e);
            e.printStackTrace();
            throw new RuntimeException(error);
        } catch (IOException e) {
            String error = Utils.obtieneMensajeErrorException(e);
            e.printStackTrace();
            throw new RuntimeException(error);
        }
        return new ResponseEntity<>(HttpStatus.OK);
    }

    /**
     * Create a new LicitacionAdjuntoRespuesta.
     */
    @ApiOperation(value = "Crea un nuevo registro de tipo LicitacionAdjuntoRespuesta", produces = "application/json")
    @PostMapping(value = "/create", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<LicitacionAdjuntoRespuesta> create(@RequestBody @Valid LicitacionAdjuntoRespuesta licitacionAdjuntoRespuesta,
            BindingResult bindingResult) throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            throw new RuntimeException(errors.toJSON());
        }
        log.debug("Ingresando Create LicitacionAdjuntoRespuestaRest : {}", licitacionAdjuntoRespuesta);
        if (licitacionAdjuntoRespuesta.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create LicitacionAdjuntoRespuesta with existing ID").body(null);
        }
        try {
            LicitacionAdjuntoRespuesta result = this.licitacionAdjuntoRespuestaDeltaService.create(licitacionAdjuntoRespuesta);
            return ResponseEntity.created(new URI("licitacionAdjuntoRespuestas/" + result.getId())).body(result);
        } catch (Exception e) {
            String error = Utils.obtieneMensajeErrorException(e);
            throw new RuntimeException(error);
        }
    }

    /**
     * Update or created LicitacionAdjuntoRespuesta.
     */
    @ApiOperation(value = "Modifica o crea registro de tipo LicitacionAdjuntoRespuesta", produces = "application/json")
    @PostMapping(value = "/save", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<LicitacionAdjuntoRespuesta> save(@RequestBody @Valid LicitacionAdjuntoRespuesta licitacionAdjuntoRespuesta,
                                                           BindingResult bindingResult) throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            throw new RuntimeException(errors.toJSON());
        }
        log.debug("Ingresando Update LicitacionAdjuntoRespuestaRest : {}", licitacionAdjuntoRespuesta);
        try {
            LicitacionAdjuntoRespuesta result = this.licitacionAdjuntoRespuestaDeltaService.save(licitacionAdjuntoRespuesta);
            return Optional.of(result).map(l -> new ResponseEntity<>(l, HttpStatus.OK)).orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            String error = Utils.obtieneMensajeErrorException(e);
            throw new RuntimeException(error);
        }
    }

    @ApiOperation(value = "guarda adjuntos", produces = "application/json")
    @PostMapping(value = "/saveAdjuntos", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<LicitacionAdjuntoRespuesta>> saveAdjuntos
            (@RequestBody @Valid List<LicitacionAdjuntoBase64Dto> licitacionAdjuntoRespuesta,
                                                           BindingResult bindingResult) throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            throw new RuntimeException(errors.toJSON());
        }
        log.debug("Ingresando Update LicitacionAdjuntoRespuestaRest : {}", licitacionAdjuntoRespuesta);
        try {
            List<LicitacionAdjuntoBase64Dto> result =
                    this.licitacionAdjuntoRespuestaDeltaService.guardarAdjuntoLicitacion(licitacionAdjuntoRespuesta);
            List<LicitacionAdjuntoRespuesta> listaAdjuntosActual = licitacionAdjuntoRespuestaRepository.findByIdLicitacionOrderByArchivoId(licitacionAdjuntoRespuesta.get(0).getIdLicitacion());
            String respuesta = "";

            respuesta = this.licitacionAdjuntoRespuestaDeltaService.enviarCorreoRespuesta(listaAdjuntosActual);

            LogTransaccion logTransaccion = new LogTransaccion();
            logTransaccion.setEnvioTrama("enviarCorreoRespuesta");
            logTransaccion.setRespuestaCodigo(respuesta);
            logTransaccion.setTipoRegistro("saveAdjuntos");
            this.logTransaccionRepository.save(logTransaccion);

            return Optional.of(listaAdjuntosActual).map(l -> new ResponseEntity<>(l, HttpStatus.OK)).orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            LogTransaccion logTransaccion1 = new LogTransaccion();
            logTransaccion1.setEnvioTrama("enviarCorreoRespuesta");
            logTransaccion1.setRespuestaCodigo(e.getMessage());
            logTransaccion1.setTipoRegistro("saveAdjuntos");
            this.logTransaccionRepository.save(logTransaccion1);
            String error = Utils.obtieneMensajeErrorException(e);
            throw new RuntimeException(error);
        }
    }


    /**
     * Delete by id LicitacionAdjuntoRespuesta.
     */
    @ApiOperation(value = "Elimina registro de tipo LicitacionAdjuntoRespuesta", produces = "application/json")
    @DeleteMapping(value = "/{id}", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {
        log.debug("Delete by id LicitacionAdjuntoRespuesta : {}", id);
        try {
            this.licitacionAdjuntoRespuestaDeltaService.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely 
            String error = Utils.obtieneMensajeErrorException(x);
            throw new RuntimeException(error);
        }
    }

    /**
     * Delete LicitacionAdjuntoRespuesta en forma total.
     */
    @ApiOperation(value = "Elimina todos los registros de tipo LicitacionAdjuntoRespuesta", produces = "application/json")
    @DeleteMapping(value = "/deleteAll", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<?> deleteAll() throws URISyntaxException {
        log.debug("Ingresando deleteAll LicitacionAdjuntoRespuestaRest");
        try {
            this.licitacionAdjuntoRespuestaDeltaService.deleteAll();
            return new ResponseEntity<>(null, HttpStatus.OK);
        } catch (Exception e) {
            String error = Utils.obtieneMensajeErrorException(e);
            throw new RuntimeException(error);
        }
    }

    protected HttpHeaders devuelveErrorHeaders(Exception e) {
        String msjError = Utils.obtieneMensajeErrorException(e);
        HttpHeaders headers = new HttpHeaders();
        headers.add("errors", Utils.obtieneMensajeErrorException(e));
        return headers;
    }

}