/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.config.BindingErrorsResponse;
import com.incloud.hcp.config.excel.ExcelType;
import com.incloud.hcp.domain.MtrTipoDocumento;
import com.incloud.hcp.repository.MtrTipoDocumentoRepository;
import com.incloud.hcp.rest._framework.AppRest;
import com.incloud.hcp.service.MtrTipoDocumentoService;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.service.support.PageResponse;
import com.incloud.hcp.util.Utils;
import io.swagger.annotations.ApiOperation;
import org.apache.poi.xssf.streaming.SXSSFWorkbook;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;
import java.io.ByteArrayOutputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.OutputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Optional;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;

@RestController
@RequestMapping(value = "/api/mtr-tipo-documento")
public class MtrTipoDocumentoRest extends AppRest {
    private final Logger log = LoggerFactory.getLogger(MtrTipoDocumentoRest.class);

    @Autowired
    protected MtrTipoDocumentoRepository mtrTipoDocumentoRepository;

    @Autowired
    protected MtrTipoDocumentoService mtrTipoDocumentoService;


    @ApiOperation(value = "Busca registro de tipo MtrTipoDocumento en base al id enviado", produces = "application/json")
    @GetMapping(value = "/findById/{id}", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<MtrTipoDocumento> findById(@PathVariable Integer id) throws URISyntaxException {
        log.debug("Find by id MtrTipoDocumento : {}", id);
        try {
            return Optional.ofNullable(this.mtrTipoDocumentoService.findOne(id).get())
                    .map(mtrTipoDocumento -> new ResponseEntity<>(mtrTipoDocumento, HttpStatus.OK)).orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
        } catch (Exception e) {
            String error = Utils.obtieneMensajeErrorException(e);
            throw new RuntimeException(error);
        }
    }


    @ApiOperation(value = "Devuelve lista de registros de tipo mtrTipoDocumento", produces = "application/json")
    @GetMapping(value = "/findAll", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<MtrTipoDocumento>> findAll() throws URISyntaxException {
        log.debug("Ingresando findAll");
        try {
            return Optional.of(this.mtrTipoDocumentoService.findAll()).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            String error = Utils.obtieneMensajeErrorException(e);
            throw new RuntimeException(error);
        }
    }


    @ApiOperation(value = "Devuelve lista de registros de tipo mtrTipoDocumento en base a los parámetros ingresados", produces = "application/json")
    @PostMapping(value = "/find", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<MtrTipoDocumento>> find(@RequestBody MtrTipoDocumento bean, BindingResult bindingResult) throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            throw new RuntimeException(errors.toJSON());
        }
        log.debug("Ingresando find by mtrTipoDocumento : {}", bean);
        try {
            return Optional.of(this.mtrTipoDocumentoService.find(bean)).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            String error = Utils.obtieneMensajeErrorException(e);
            throw new RuntimeException(error);
        }
    }

    @ApiOperation(value = "Devuelve lista de registros de tipo mtrTipoDocumento en base a los parámetros ingresados", produces = "application/json")
    @GetMapping(value = "/findByCodigoAgrupadoArchivo/{codigoAgrupadoArchivo}", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<MtrTipoDocumento>> findByCodigoAgrupadoArchivo
            (@PathVariable("codigoAgrupadoArchivo") String bean) throws URISyntaxException {

        log.debug("Ingresando find by mtrTipoDocumento : {}", bean);
        try {
            return Optional.of(this.mtrTipoDocumentoService.findCodigoAgrupado(bean)).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));

        } catch (Exception e) {
            String error = Utils.obtieneMensajeErrorException(e);
            throw new RuntimeException(error);
        }
    }


    @ApiOperation(value = "Devuelve lista de registros paginados de tipo mtrTipoDocumento", produces = "application/json")
    @PostMapping(value = "/findPaginated", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<MtrTipoDocumento>> findPaginated(@RequestBody PageRequestByExample<MtrTipoDocumento> prbe, BindingResult bindingResult)
            throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            throw new RuntimeException(errors.toJSON());
        }
        log.debug("Ingresando findPaginated by PageRequestByExample : {}", prbe);
        try {
            PageResponse<MtrTipoDocumento> pageResponse = this.mtrTipoDocumentoService.findPaginated(prbe);
            return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
        } catch (Exception e) {
            String error = Utils.obtieneMensajeErrorException(e);
            throw new RuntimeException(error);
        }
    }


}