/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/mapper/EntityMapper.java.e.vm
 */
package com.incloud.hcp.myibatis.mapper;

import com.incloud.hcp.domain.ActaSustento;
import com.incloud.hcp.domain.AppProcesoLog;
import com.incloud.hcp.domain.Licitacion;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@Mapper
@Repository
public interface ActaSustentoMapper {

    List<ActaSustento> getListActaSustentoByFiltroPaginado(
            @Param("numeroActaSustento") String numeroActaSustentoString,
            @Param("annioActa") Integer annioActa,
            @Param("idProveedor") String idProveedor,
            @Param("nombreProveedor") String nombreProveedor,
            @Param("nroRegistros") Integer nroRegistros,
            @Param("paginaMostrar") Integer paginaMostrar
    );

    List<ActaSustento> getListActaSustentoByFiltroPaginadoProveedor(
            @Param("numeroActa") String numeroActaSustentoString,
            @Param("annioActa") Integer annioActa,
            @Param("idProveedor") String idProveedor,
            @Param("nombreProveedor") String nombreProveedor,
            @Param("nroRegistros") Integer nroRegistros,
            @Param("paginaMostrar") Integer paginaMostrar

    );

    List<ActaSustento> getListActaSustentoByFiltroPaginadoProveedorRechazada(
            @Param("numeroActaSustento") Integer numeroActaSustentoString,
            @Param("annioActa") Integer annioActa,
            @Param("idProveedor") String idProveedor,
            @Param("nombreProveedor") String nombreProveedor,
            @Param("nroRegistros") Integer nroRegistros,
            @Param("paginaMostrar") Integer paginaMostrar
    );
}